### ISSUE TITLE
Women in science and computing photography project

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#103]
Here's some info about a photography project being done by Julie Pasila, a local photographer. She's looking for women who code in particular, so I told her I'd pass on the info to this group! 

---

I'm currently looking for subjects to participate in a photography project about women who work in scientific fields. Ideally, this project will be comprised of portraits as well as images describing research (when possible). The final form of the project will most likely be a book and public exhibition, so participants will be required to sign model release forms. A time commitment of approximately two hours will be needed from each participant to complete a photo shoot and small interview (one or two additional meetings may be needed depending on the kind of research being done). There's currently no firm timeline for the completion of this project, so anyone who may be interested can choose to participate now or at a later date.

Email: juliepasila@gmail.com

**Comment by lwjohnst86** [comment]
Assuming this is done.
