### ISSUE TITLE
Hi everyone!

### ISSUE THREAD

**Issue by joelostblom** [UofTCoders/studyGroup#110]
Hi, I just found this group and thinks it looks really interesting, so I wanted to introduce myself. I have started learning to code the last couple of years in my PhD and I have some experience in Pandas, Seaborn and basic R.

I'm sad I didn't find this group earlier, so that I could have joined for the gthub lecture today (I don't understand branches very well...), but I am looking forward to the next event! I will try to come out to the coding session, I assume everyone just sits together and work on their own stuff during these, is that accurate?

Cheers,
Joel

**Comment by mbonsma** [comment]
Hi Joel, welcome! You're right, during the coworking sessions we mostly just work on our own thing or chat about something we're working on. Last week we tried something new, which was having people work in pairs, so in the future the coworking sessions might start to look a little different. Either way, those are good for getting to know people, so it would be great to see you next week!

Also, we recorded last night's session for the first time, so if you're interested you can check out the [video](https://www.youtube.com/watch?v=nRUW6LLkCqQ)! And the [lesson text](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/gitBranches/lesson.md) is posted in this repo as well.

**Comment by joelostblom** [comment]
Great, thanks for the links and see you next week!
