### ISSUE TITLE
Executive Elections - April 21st

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#112]
Hi Everyone,

Are you interested in helping out behind the scenes and working towards improving how the Study Group runs? If so, you might want to run for one of the executive positions in the upcoming elections **Thursday, April 21st, 2016**. 

The positions available are:
- President (must have previously been to at least 5 meetings, either attending or leading a session)
- Technical Admin
- Admin
- Treasurer

For descriptions of these roles, click [here](https://github.com/UofTCoders/council/blob/master/Council_Roles.md).

If you'd like to nominate someone or yourself for a position, please reply to this issue with the name and for which executive position. Nominees are asked to prepare a short (2-3 minute) spiel to give at the April 21st meeting (during which members will have the opportunity to vote) about themselves, why they're running, and how they'd like to contribute to the executive council.

_If you are unable to attend on this day, but still wish to run for a position, please send a brief statement to utorontostudygroup@gmail.com. We will read your statement in your place at the elections._

Whether you are running or not, make sure you come out to vote!
Hope to see you there!

**Comment by lwjohnst86** [comment]
Guess I'll start. I've been interim Treasurer since the group became official in Jan (ish) and I'd like to continue being Treasurer. :)

**Comment by mbonsma** [comment]
I've been interim President since the group started, and I'd like to nominate myself to continue in that role.

**Comment by QuLogic** [comment]
I too have been interim Technical Admin since the group started, and I'd like to nominate myself to continue in that role.

**Comment by linamnt** [comment]
I'll nominate myself for (regular) Admin.
