### ISSUE TITLE
UofT Journal Access Bookmarklet

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#118]
I'm sure we all know the hassle of trying to get access to an article/the right authentication screen when we're not on campus internet . A recent discussion revealed that many people (n=5) would appreciate a simple solution to this problem that does not involve manually typing in myaccess.library.utoronto.ca to urls, so thought it'd be nice to share some ways to make life a tad bit easier!

**Zotero Browser Extension**
Apparently [Zotero](https://www.zotero.org/download/) (browser extension and the standalone) citation manager, can be set to use the proxy when you're not on campus i.e. the domain is not utoronto.ca ( @QuLogic correct me if I'm wrong!)

**Browser Bookmarks**
Another way is to use a bookmarklet modified to get the uoft proxy version of the site ( currently for chrome, haven't tested it in other browsers, but I'm sure an analagous solution is available!) 

Here's how to do it in Chrome:
1. Create a new bookmark (multiple ways...e.g. go to bookmark manager, right-click, Add Page)
2. In the popup window, set the Name to whatever you like, e.g. UofT Library Access
3. copy this into the url: 
`javascript: window.location = window.location.protocol + '//' + window.location.hostname + '.myaccess.library.utoronto.ca' + window.location.pathname;`
4. Hit Save and drag it to your bookmarks toolbar

Also, there may even be a chrome extension on the way made by one of our own! (apologies for the chrome bias)

Enjoy!

**Comment by joelostblom** [comment]
Thanks for the tips! I have been using Zotero in Firefox for a while and I can confirm that this solution works really well. I also use the [UofT my.access bookmarklet](http://guides.library.utoronto.ca/proxy), so whenever I encounter a domain not saved in Zotero yet, I just hit <kbd>Ctrl + b</kbd> to show the bookmarks bar, click the bookmarklet and login, and then <kbd>Ctrl + b</kbd> again to hide the bookmarks bar. It's quite convenient, and there will be a Zotero popup with the option to automatically redirect future visits to that domain via the UofT proxy.

**Comment by linamnt** [comment]
Nice! I didn't realize UofT Libraries made it's own bookmarklet! Makes this solution even easier, and applicable accross browsers :)

**Comment by 2ufotofu2** [comment]
I've used [U of T's VPN](http://vpn.utoronto.ca/). This is particularly useful if you need to access several different journals in the same session, as it doesn't require any sort of login once you've connected to the VPN.
