### ISSUE TITLE
Are there any good R programming challenges out there for beginners?

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#121]
I know of [codewars](http://www.codewars.com/), but I don't think they have any R challenges. @linamnt, you might have mentioned some during the paired programming workshop I missed, but can we record them here?

**Comment by linamnt** [comment]
I don't think there are as many uniquely for R but here are two options:
1. http://r-exercises.com/category/exercises/ which is very different from
   codewars, it's a blog with exercises by topic but very helpful I think.
2. the general purpose https://projecteuler.net/archives for math/logic
   problems for programming

On Tue, Apr 26, 2016 at 9:50 AM, Madeleine Bonsma notifications@github.com
wrote:

> I know of codewars http://www.codewars.com/, but I don't think they
> have any R challenges. @linamnt https://github.com/linamnt, you might
> have mentioned some during the paired programming workshop I missed, but
> can we record them here?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/121

## 

Lina Tran
MSc. Candidate | Frankland Lab http://www.franklandlab.com/
Department of Physiology
University of Toronto
