### ISSUE TITLE
Make another repo for events only 

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#13]
It was mentioned at yesterday's meetup that Github sends too many notifications for people who only want to be notified about events. @QuLogic suggested creating another repo for events only, that way people can choose whether to watch the events-only repo, the repo for all other activity, or both.(In the meantime, if you want to [unsubscribe](https://help.github.com/articles/unsubscribing-from-conversations/) from specific issues, click 'unsubscribe' on the right for those issues.)

I think this is simply a matter of making a new repo called 'Events' and then copying the necessary page  stuff to make it work.

**Comment by lwjohnst86** [comment]
Actually, you probably don't even need to add anything to the repo, just make issues that broadcast the event and add a link in the issue to the main repo/page.

**Comment by mbonsma** [comment]
Yeah, you're right. Nothing too fancy needed. I'll try it out now.

**Comment by QuLogic** [comment]
We should probably link [that repo here](https://github.com/UofTCoders/Events).

**Comment by mbonsma** [comment]
I added some instructions and a link in the ReadMe - anywhere else it should go?

**Comment by QuLogic** [comment]
No, I was referring to this ticket itself, since it's about it.

**Comment by QuLogic** [comment]
This was implemented and seems to be working well enough.
