### ISSUE TITLE
Tentative Summer Schedule 

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#140]
Hi Everyone,

Based on the survey results, we've compiled the most requested lessons for this summer session! However, we do need instructors for these lessons, so here's your opportunity to share your knowledge and skills with the UofT Coders community :) 

**If you're interested in instructing a lesson or doing a demo from the list, comment below and let us know if the weeks work for you,** if not we can shuffle things around and make it work. 

~~June 9 - Intro to Python - Sina~~
~~June 16 - Intro to SQL Databases - Jon Pipitone~~
~~June 23 - Lightning Demos: Show us your academic workflows - Dawn, Madeleine~~
~~June 30 - Week off for Canada Day~~
~~July 7 - Coworking Session~~
July 14 - Debugging in Python - John Ladan
July 21 - Plotting with ggplot2 in R - Sarah
July 28 - Coworking Session
August 4 -  Lightning Demos: Data Visualization (All Languages) - Madeleine, Brian Sutherland (D3.js), Luke (R ggvis), Derek
August 11 - Coworking Session
August 18 - Class Structure in Python - Lina
August 25 - Large Datasets in Python - Wei Zhan

**Comment by dcwalk** [comment]
Hey @linamnt I am super keen on the academic workflow session and would love to do a lightning demo (and perhaps rope one or two Faculty of Information people in), unfortunately I'm out of town after July 11 😢 

Are these dates fixed?

**Comment by linamnt** [comment]
Hey @dcwalk the dates definitely are not fixed and we can change them based
on the instructors willing to lead them :) Is there an optimal week (prior to Jul 11) for you
that we can change it to?

On Fri, May 27, 2016 at 8:44 AM, dcwalk notifications@github.com wrote:

> Hey @linamnt https://github.com/linamnt I am super keen on the academic
> workflow session and would love to do a lightning demo (and perhaps rope
> one or two Faculty of Information people in), unfortunately I'm out of town
> after July 11 😢
> 
> Are these dates fixed?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/140#issuecomment-222136759,
> or mute the thread
> https://github.com/notifications/unsubscribe/AKQ2vsppYDyYYn-YTi066hZoWuyw0ghTks5qFucYgaJpZM4InuG8
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab http://www.franklandlab.com/
Department of Physiology
University of Toronto

**Comment by dcwalk** [comment]
Would swapping the Lightning Demos work?  June 23 is a good date for me!

**Comment by QuLogic** [comment]
We should do a key signing for the reimbursements at some point.

**Comment by linamnt** [comment]
Cool sounds good, I've changed it!

**Comment by linamnt** [comment]
@QuLogic

**Comment by iandennismiller** [comment]
I'd also like to demo my workflow.  I presented this 3 years ago at St. George WIDEN:

http://www.widen.ca/2013/03/10/on-networks-march-21-2013/

However, I can shorten it to about 5 minutes.

**Comment by linamnt** [comment]
Great thanks! I've added you to the list Ian!

**Comment by dcwalk** [comment]
~~Oop, missed your comment @QuLogic, haha can I just get the reimbursements?!~~
~~We could save the encryption and keysigning for an upcoming session "Security and your Research Data"  :key: :lock:~~

Edit: ahahah okay sorry totally missed the plot, I guess you want me to verify FOR the [reimbursement](

**Comment by ghost** [comment]
i can probably do ggplot2 again!

**Comment by QuLogic** [comment]
> We could save the encryption and keysigning for an upcoming session "Security and your Research Data" :key: :lock:

I suggested doing it at one of our co-working sessions, but you won't be here for them?

> Edit: ahahah okay sorry totally missed the plot, I guess you want me to verify FOR the reimbursement.

For _signing_ of the reimbursement request, but @lwjohnst86 already did that, so I guess as long as he trusts himself, it's fine...

**Comment by linamnt** [comment]
that'd be great, thanks @thesarahmeister 

also, @QuLogic the next coworking session is Jul 14, does that work? But as you said maybe people can be reimbursed the old fashioned way before then?

**Comment by iandennismiller** [comment]
Hi @linamnt - can I confirm what time of day the lightning sessions will be on June 23?  If it's at 4pm or later, I will need to remove myself from the list.  Sorry for the trouble!

**Comment by linamnt** [comment]
It will be at 6pm, sorry about that! Hopefully you can join us another time!

On Thu, Jun 9, 2016 at 12:25 AM, Ian Dennis Miller <notifications@github.com

> wrote:
> 
> Hi @linamnt https://github.com/linamnt - can I confirm what time of day
> the lightning sessions will be on June 23? If it's at 4pm or later, I will
> need to remove myself from the list. Sorry for the trouble!
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/140#issuecomment-224797060,
> or mute the thread
> https://github.com/notifications/unsubscribe/AKQ2vuaFfD4qR4p8zbfs5cxQ4uLdPU1aks5qJ5WwgaJpZM4InuG8
> .

## 

Lina Tran
PhD Student | Frankland Lab http://www.franklandlab.com/
Department of Physiology
University of Toronto

**Comment by mbonsma** [comment]
I can do something for the academic workflows and visualization lightning demos :smile:

**Comment by linamnt** [comment]
Cool! I also put myself down for the class structure in Python again.

**Comment by lwjohnst86** [comment]
I can do one for the viz lightning demo.
