### ISSUE TITLE
Call for helpers for upcoming CUPE x UofT Coders workshops

### ISSUE THREAD

**Issue by lcoome** [UofTCoders/studyGroup#147]
In cooperation with CUPE, UofT Coders will be hosting a series of three workshops aimed at giving postdoctoral fellows at U of T a brief introduction to data analysis and visualization in Python which will be largely based on the [SWC Python](http://swcarpentry.github.io/python-novice-inflammation/) lesson materials. The dates are **July 27, Aug 3, and Aug 10,** and the workshops will run in the evenings. 

We are seeking people to volunteer as helpers for some or all of these sessions (as many as you'd like). You don't need to be an expert on Python to be a helper. If you feel comfortable being able to work through participant questions (often about troubleshooting the programs or setup, but also about the topics being taught) or even the know-how to search for the answers on the internet, we'd love to have you help out at our workshops! It's a great opportunity to get involved with a great group of people and put your skills to use!

If you're interested, reply to this issue or send an email to [lindsay.coome@mail.utoronto.ca](mailto:lindsay.coome@mail.utoronto.ca) with which **session(s)** you'd like to help with.

**Comment by gattacagithub** [comment]
Hi,

My name is Wei and I am a former student of the Python lesson. Now I have a very good understanding of the class material. In my research I use Python a lot and am familiar with many of the common problems. It would be a pleasure for me to help out other students.

I am available for all the dates (July 27, Aug 3, and Aug10). Let me know if I can be of any help.

Thanks!

Wei

**Comment by lwjohnst86** [comment]
These were evenings right? I could help July 27th or Aug 10th.

**Comment by lcoome** [comment]
Yes, evenings! And awesome, we'd be happy to have your help Wei. The sessions will run from 5:30pm-8:00pm in Sid Smith room 1088.
