### ISSUE TITLE
Roof party! Friday July 15

### ISSUE THREAD

**Issue by kgeier** [UofTCoders/studyGroup#149]
336 Spadina avenue (entrance 2nd floor next to Alice hair salon). Rooftop between chinatown and kensignton market. View of the city, good people, and DJs playing chill and dance music. 

For Kirk's friend's birthday but coders are more than welcome (it's a big roof, and the coders are a pretty cool gang). Luke is coming! 

See you tomorrow (Friday July 15). Some people are arriving 8:30 to catch sunset, others before midnight, so come whenever.

**Comment by josephdviviano** [comment]
wat
