### ISSUE TITLE
Session proposals - master

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#15]
Comment with proposed sessions, and if possible volunteer yourself or someone you know to lead a session. Even better, choose a date that you could lead it! 

As of now, Thursday 6pm - 7pm is still the most popular time. Fill out the [Doodle poll](http://doodle.com/xubabx65hd954zs3) if you haven't yet. 

If your topic is short, we can group several topics together into a **coding lightning demo**. 

Sample comment:

**Topic:** Regular expressions in Python
**Presenter:** Madeleine (@mbonsma)
**Dates:** Any except July 9
**Proposed length:** Lightning demo

**Comment by mbonsma** [comment]
**Topic:** Creating versatile plots in Python - matplotlib
**Presenter:** Ricardo @ricardoharripaul
Dates: ?
Length: ?

**Comment by cczhu** [comment]
**Topic:** Beginner's guide to Python
**Presenter:** Charles @cczhu
**Dates:** ?
_Proposed length:_\* 1 hour

**Comment by mbonsma** [comment]
**Topic:** Phylogenomics / de novo transcriptome assembly / BLAST and variant tools / sequence alignment / building gene trees
**Presenter:** Matt @MattStata

**Comment by ricardoharripaul** [comment]
I think we should have the beginner guide to python before making graphs in Python.  If people don't mind.

What does everyone else think?

**Comment by mbonsma** [comment]
Agreed. Charles is going to do the Intro to Python code-along on July 9.

**Comment by mbonsma** [comment]
It would be cool to have an **Intro to R** session as well - I know lots of people were interested in R.

**Comment by lwjohnst86** [comment]
What does the 'master' part of the issue title mean?

**Topic**: Intro to R and data wrangling in R
**Presenter**: Luke (me!)
**Dates**: Mid-to-late July, anytime August
**Proposed length**: 1 hr

**Comment by mbonsma** [comment]
By 'master' I meant that this is an aggregate of all the separate topic threads, and this is where actual sessions get planned as opposed to just suggesting topics. It can definitely be changed to a different name.

**Comment by lannajin** [comment]
I could potentially give an intro to R session, but in the moment busy with defense stuff. Could most likely host an intro to R session at the end of August for those interested.

Edit: Just realized Luke has offered to host an R session. I could do instead a tutorial on R Shiny (interactive graphics in R)

**Comment by mbonsma** [comment]
A thought - we could use the [wiki](https://github.com/UofTCoders/studyGroup/wiki) to assemble a list of session ideas and edit it as we go. What do people think?

**Comment by lwjohnst86** [comment]
:+1:  for @lannajin suggestion for R Shiny! I would be interested.

Also, :+1: to the wiki idea! I just got it started [here](https://github.com/UofTCoders/studyGroup/wiki/Session-Proposals) if anyone wants to look it over.

**Comment by ricardoharripaul** [comment]
Sounds good.  FOr R shiny you need to install a server.  it is a bit slow.
Someone in my previous lab made a data browser with it.

**Comment by lannajin** [comment]
There's also http://www.shinyapps.io/, which doesn't require setting up a server.

**Comment by mbonsma** [comment]
@lwjohnst86 - How do you feel about doing Intro to R next week (July 23)?

**Comment by lannajin** [comment]
I could do the Shiny R tutorial on July 30th. Or, alternatively the 20th (maybe) or 27th (definitely).

**Comment by lwjohnst86** [comment]
Hmm, yea I could. I'll setup a event issue tomorrow with details. 

On 16 July, 2015 7:50:43 PM EDT, mbonsma notifications@github.com wrote:

> @lwjohnst86 - How do you feel about doing Intro to R next week (July
> 23)?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/UofTCoders/studyGroup/issues/15#issuecomment-122132656

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mbonsma** [comment]
@lannajin I like the idea of Shiny R on July 30 - a nice run of R. @lwjohnst86 - awesome!

**Comment by ricardoharripaul** [comment]
I can prepare something for the plotting functions.  I was actually
planning on doing that this weekend.  Also,  D3 is really cool.

**Comment by mbonsma** [comment]
@ricardoharripaul - we talked about D3 tonight! We were thinking a session on D3 would be cool.

**Comment by ricardoharripaul** [comment]
It would be great.  I have some code.  Angular Js and NodeJs are pretty
cool too but they are somewhat more complicated.

**Comment by lannajin** [comment]
Yes please teach me the ways of D3 and javascript!!!! I have a book on D3 if you'd like to use it. Would like to know, specifically, how to filter data for specific variables.

**Comment by ricardoharripaul** [comment]
I have some tutorials if you would like them.

**Comment by mbonsma** [comment]
@ricardoharripaul - sorry for the scheduling confusion. As of now we have Intro to R this Thursday (July 23) followed by Shiny R (July 30). Would August 13 work for you for matplotlib? Other August Thursdays would be an option too (I won't be around on August 6). 

@lannajin - do you have a preference for which day you do Shiny R, July 30 or sometime in August?

**Comment by ricardoharripaul** [comment]
These times can work I just have to know.

Ricardo

**Comment by mbonsma** [comment]
@ricardoharripaul it's up to you. Pick your favourite Thursday in August, and it's yours! Once you pick, I'll update the [wiki](https://github.com/UofTCoders/studyGroup/wiki/Session-Proposals) with the date and create an event listing.

**Comment by lannajin** [comment]
@mbonsma I was planning to present the stuff I've presented before to my two labs, so I already have something together for the Shiny tutorial. So I'm pretty agnostic as to what particular day I present (so long as I'm in town). I'll let you figure out the best date and I'll roll with it.

**Comment by ricardoharripaul** [comment]
I can do the sixth.

**Comment by mbonsma** [comment]
Okay so we've got @lannajin on the 30th and @ricardoharripaul on the 6th. Sounds good! (Ricardo, I'll have to catch up on your material another time, I'll be sorry to miss it!)

**Comment by mbonsma** [comment]
@lannajin, I made an [issue](https://github.com/UofTCoders/Events/issues/5) for this Thursday. Can you check it over and add anything people should do in preparation?

**Comment by lannajin** [comment]
I'm totally confused how I'm supposed to create a new directory within
lessons and upload my own...

On Tue, Jul 28, 2015 at 11:00 AM, mbonsma notifications@github.com wrote:

> @lannajin https://github.com/lannajin, I made an issue
> https://github.com/UofTCoders/Events/issues/5 for this Thursday. Can
> you check it over and add anything people should do in preparation?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/15#issuecomment-125639854
> .

## 

Lanna Jin
PhD Candidate
Cadotte Lab & Fortin Spatial Ecology Lab
Dept. of Ecology & Evolutionary Biology
University of Toronto

Mobile: (647) 721-7722
lanna.jin@mail.utoronto.ca
http://individual.utoronto.ca/lannajin

**Comment by mbonsma** [comment]
@lannajin are you using Git Bash to do stuff? If so, you can create a folder in your forked or local version and then push it to Github. 

Or, if you just want to stay on the website, you can make a new folder by clicking the '+' in the 'lessons' folder and typing your folder name and then a slash (I got this from [here](http://stackoverflow.com/questions/18773598/creating-folders-inside-github-com-repo-without-using-git)). Then you can create a file, name it whatever you want, and paste whatever you want in there.

**Comment by lwjohnst86** [comment]
Here's a step-by-step in case others want to know too:
1. Fork the `studyGroup` into your GitHub account
2. `git clone` your new forked version of `studyGroup` onto your computer, if you want into your Desktop (`cd Desktop; git clone yoururl` replacing yoururl with the URL provided on your GitHub studyGroup repo, for example mine would look like: `git clone https://github.com/lwjohnst86/studyGroup.git`)
3. `cd studyGroup` and `git status` or `git log` to confirm you are there and to see what's going on in the new repo.
4. Add the original Study Group repo using this command: `git remote add upstream https://github.com/UofTCoders/studyGroup.git`
5. Create a folder in the `lessons` directory on your computer.
6. Create a file.
7. `git add newfile` and `git commit -m "Added file on lesson"`
8. Push up to your GitHub `git push origin gh-pages`
9. Submit a Pull Request _from_ your GitHub account _into_ the UofTCoders.

Does that help?

**Comment by lannajin** [comment]
Can someone else do this for me (@mbonsma)? My defense is tomorrow and I've spent the last hour poking around GitHub trying to get it to work. I think I'm going to give up. I've emailed @mbonsma the files...@lwjohnst86, I will try your method next time...

**Comment by mbonsma** [comment]
I'm on it!

**Comment by lwjohnst86** [comment]
I've put together a wiki on those unfamiliar with GitHub, but who want to contribute a lesson: https://github.com/UofTCoders/studyGroup/wiki/Contributing-a-lesson

**Comment by mbonsma** [comment]
Amazing! Thanks @lwjohnst86, that looks great!

**Comment by QuLogic** [comment]
> My defense is tomorrow

And you're still trying to work on this! That's some dedication there...

**Comment by mbonsma** [comment]
@ricardoharripaul, are you good to go for this Thursday (the 6th)? If so, feel free to create an event issue [here](https://github.com/UofTCoders/Events/issues) (or I can, just let me know), and then either you or I can make the post for the website (examples [here](https://github.com/UofTCoders/studyGroup/tree/gh-pages/_posts), instructions [here](https://github.com/mozillascience/studyGroup#how-to-launch-a-new-event)).

**Comment by ricardoharripaul** [comment]
Hey,

I created a new issue and a short description.  I am assuming it is in Rm.
408.

**Comment by mbonsma** [comment]
Yes, 408! That's perfect, thanks!

**Comment by mbonsma** [comment]
Group poll: how about a coworking or discussion session for our meetup on August 13th? 
The idea of themed coworking sessions was brought forward a few weeks ago - how about a discussion on plotting in response to the R and Python plotting sessions of the last two weeks?

**Comment by ricardoharripaul** [comment]
As in using ggplot2 and python to graph the same data or are we seeing how
people liked the different sessions.

**Comment by mbonsma** [comment]
I was thinking more like a personal show-and-tell, maybe ways people have applied things from the sessions or other tricks and tools people use for plotting, or as a place for people to bring questions more informally.

**Comment by lannajin** [comment]
@mbonsma that's a great idea that will hopefully lead to a fruitful session. Unfortunately I'm out of town until the week of the 20th...pretty bummed to have to miss out on both the python plotting and coworking sessions!

**Comment by mbonsma** [comment]
@lannajin this is one I think we could do more than once, especially once a new term starts.

**Comment by lwjohnst86** [comment]
And we haven't really had a formal session on graphing in R... I would definitely come just to hear others thoughts and experiences! 

On 4 August, 2015 11:15:28 AM EDT, mbonsma notifications@github.com wrote:

> I was thinking more like a personal show-and-tell, maybe ways people
> have applied things from the sessions or other tricks and tools people
> use for plotting, or as a place for people to bring questions more
> informally.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/UofTCoders/studyGroup/issues/15#issuecomment-127646023

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mbonsma** [comment]
Is anyone interested in presenting this week, or does anyone have suggestions? (See the [wiki](https://github.com/UofTCoders/studyGroup/wiki/Session-Proposals) for a list of our current ideas.)

Some options, pulled from the wiki:
- Phylogenomics / de novo transcriptome assembly / BLAST and variant tools / sequence alignment / building gene trees - @MattStata
- Versatile academic writing from the command line with Pandoc - @adunning
- Unit testing in Python - @aerler
- Web APIs: HTTP, REST, JSON - @jamesaoverton

**Comment by lannajin** [comment]
I could do the Phylogenomics bit if it's something like this that people
are interested in:
https://docs.google.com/document/d/16r-wbb1BlfeO6FM2d5pojeQnJQEjgOLVN_iB7tWLVuk/pub

On Mon, Aug 17, 2015 at 10:05 AM, mbonsma notifications@github.com wrote:

> Is anyone interested in presenting this week, or does anyone have
> suggestions? (See the wiki
> https://github.com/UofTCoders/studyGroup/wiki/Session-Proposals for a
> list of our current ideas.)
> 
> Some options, pulled from the wiki:
> 
>    -
> 
>    Phylogenomics / de novo transcriptome assembly / BLAST and variant
>    tools / sequence alignment / building gene trees - @MattStata
>    https://github.com/MattStata
>    -
> 
>    Versatile academic writing from the command line with Pandoc -
>    @adunning https://github.com/adunning
>    -
> 
>    Unit testing in Python - @aerler https://github.com/aerler
>    -
> 
>    Web APIs: HTTP, REST, JSON - @jamesaoverton
>    https://github.com/jamesaoverton
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/15#issuecomment-131828677
> .

## 

Lanna Jin
PhD Candidate
Cadotte Lab & Fortin Spatial Ecology Lab
Dept. of Ecology & Evolutionary Biology
University of Toronto

Mobile: (647) 721-7722
lanna.jin@mail.utoronto.ca
http://individual.utoronto.ca/lannajin

**Comment by mbonsma** [comment]
That looks sweet! I don't know what @MattStata had in mind - maybe you could do a joint thing? Although that might be more work than one person leading something. 

Anyone else want to add suggestions or preferences?

**Comment by lannajin** [comment]
Maybe we could all do three minute thesis presentations. Or, we could all
quickly do a three to five minute blurb on something (a program,
library/package, resource, tool, etc.) that we've currently discovered or
have been using lately that we'd like other people to know about.

On Monday, August 17, 2015, mbonsma notifications@github.com wrote:

> That looks sweet! I don't know what @MattStata
> https://github.com/MattStata had in mind - maybe you could do a joint
> thing? Although that might be more work than one person leading something.
> 
> Anyone else want to add suggestions or preferences?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/15#issuecomment-132023262
> .

## 

Lanna Jin
PhD Candidate
Cadotte Lab & Fortin Spatial Ecology Lab
Dept. of Ecology & Evolutionary Biology
University of Toronto

Mobile: (647) 721-7722
lanna.jin@mail.utoronto.ca
http://individual.utoronto.ca/lannajin

**Comment by lannajin** [comment]
Shoot, I just realized I double booked for Thursday. I already committed to
subbing for a team on Thursday. sorry :(

On Mon, Aug 17, 2015 at 9:41 PM, Lanna Jin lannajin@gmail.com wrote:

> Maybe we could all do three minute thesis presentations. Or, we could all
> quickly do a three to five minute blurb on something (a program,
> library/package, resource, tool, etc.) that we've currently discovered or
> have been using lately that we'd like other people to know about.
> 
> On Monday, August 17, 2015, mbonsma notifications@github.com wrote:
> 
> > That looks sweet! I don't know what @MattStata
> > https://github.com/MattStata had in mind - maybe you could do a joint
> > thing? Although that might be more work than one person leading something.
> > 
> > Anyone else want to add suggestions or preferences?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/UofTCoders/studyGroup/issues/15#issuecomment-132023262
> > .
> 
> ## 
> 
> Lanna Jin
> PhD Candidate
> Cadotte Lab & Fortin Spatial Ecology Lab
> Dept. of Ecology & Evolutionary Biology
> University of Toronto
> 
> Mobile: (647) 721-7722
> lanna.jin@mail.utoronto.ca
> http://individual.utoronto.ca/lannajin

## 

Lanna Jin
PhD Candidate
Cadotte Lab & Fortin Spatial Ecology Lab
Dept. of Ecology & Evolutionary Biology
University of Toronto

Mobile: (647) 721-7722
lanna.jin@mail.utoronto.ca
http://individual.utoronto.ca/lannajin

**Comment by mbonsma** [comment]
I really like that idea though! If nobody has a burning desire to do something else, I'll set that up.

**Comment by QuLogic** [comment]
There are already some lightning talks on the suggestion page...

**Comment by mbonsma** [comment]
Yeah. It looks like it's just @QuLogic and me outside of a larger suggested framework. Elliott, do you want to do the IPython demo? I can do a bit about regular expressions in Python. 

Is anyone else interested in giving a 5-10 minute blurb about something? If not, we can just do those two and open the floor for contributions on Thursday.

**Comment by aerler** [comment]
I could do a Unittest intro next week, but at the moment I'm still busy with Thesis corrections.
Generally speaking, I like the idea of short thesis presentations, so we know what others are doing; obviously we would focus more on the computational aspect.
Something else we could have is presentations about some code we've written that's maybe a bit more self-contained and might be useful or at least understandable outside our own field.
For example @dchandan has written a GUI program to edit gridded fields (arrays) with the mouse.

**Comment by mbonsma** [comment]
Okay so this Thursday we'll do short presentations from me, possibly @QuLogic, and we can add anyone else either between now and Thursday or impromptu on the day. 

@aerler, your unit testing session next week would be great.

**Comment by lwjohnst86** [comment]
Closing as this has moved into the [wiki section](https://github.com/UofTCoders/studyGroup/wiki) since last fall term
