### ISSUE TITLE
Fall 2016 Schedule (Tentative) - Instructors Needed

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#156]
Hi Everyone, 

After viewing the doodle results, we will be switching our sessions to **Wednesdays at 6pm** starting September 7th, where we will open the semester with a hacky hour at the GSU Pub. Everyone is welcome to attend, new and returning members. 

Below is a list of the tentative schedule of lessons/topics. If you would like to instruct one of these classes, please comment below. **We are flexible on the dates so if the date listed doesn't work for you, let us know which week would be best for you!**
(Bolded = Instructor Needed)
- Hacky Hour (GSU Pub) - September 7
- Intro Python - September 14 - Lina
- Intro R - September 21 - Zoe
- Git themed coworking session - September 28
- **Cartography and Mapping in Python - October 5**
- Making Packages in R - October 12 - Luke
- Coworking session - October 19
- Intro Bash - October 26 - John
- Databases SQL - November 2 - Ian
- LaTeX - November 9 - Anita
- Careers outside academia discussion - November 16 
- Web Design with Jekyll/Github Pages - November 23 - Luke
- Pandoc and Markdown - November 30 - Dano
- Coworking Session - December 7

**Comment by dcwalk** [comment]
Hey! Would definitely be up to lead a session, there are a few on there that would work, I'll leave it to others for a bit as I figure out my schedule too!

**Comment by ghost** [comment]
Is there any way to attend session remotely?

**Comment by linamnt** [comment]
@drashti4 We usually livestream our lessons via google hangouts, so check out the event page (https://github.com/UofTCoders/Events/issues) for the link as the lesson starts, or you can view it afterwards at your convenience!

**Comment by linamnt** [comment]
I could do Intro Python Sep 14th.

**Comment by zoelynnfrancis** [comment]
I'd like to do the Intro to R session on September 21st.  I'm excited that I'll be able to attend meetings this year, now that they are on Wednesdays!

**Comment by dcwalk** [comment]
Ach, looks like I won't be able to attend this semester as I have a course on Wednesday evenings 😭 
I'll have to check out the recorded hangouts.

**Comment by iandennismiller** [comment]
It was nice to meet some of you at the Hacky Hour last week.  I'm happy to cover SQL on November 2.  Also, I will be coming to the Weds meetings semi-regularly - see you then!

**Comment by linamnt** [comment]
Hi @iandennismiller 
Would you be able to send your email to uoftcoders@gmail.com so we can send you some resources for teaching lessons with our group?
