### ISSUE TITLE
"Talk to us" button on website not working?

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#157]
When I click the "Talk to us" button (under "Contact"), it just bounces back to the top of the page, it doesn't redirect to the GitHub issues.

**Comment by QuLogic** [comment]
Odd, that link comes from [here](https://github.com/UofTCoders/studyGroup/blob/gh-pages/_includes/contact.html#L11), using `site.github.issues_url` so it should be populated by GitHub. Maybe they've got a bug? Hopefully it will be correct itself the next time we re-generate the site with a new commit.

**Comment by lwjohnst86** [comment]
Seem to work now.
