### ISSUE TITLE
Members Listing on Website 

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#158]
Hi Everyone, 

We're updating the website and the members list on the website (see Who We Are at https://uoftcoders.github.io/studyGroup/#contact ). If you would like to remain on the members list, please comment or thumbs up/+1 this post. 

Thanks!

**Comment by ghost** [comment]
+1

**Comment by NasheedM** [comment]
+1

Nasheed

**Comment by lcoome** [comment]
+1

**Comment by tkivisik** [comment]
+1

**Comment by lwjohnst86** [comment]
See PR https://github.com/UofTCoders/studyGroup/pull/203
