### ISSUE TITLE
Earth and Atmospheric Science Topics

### ISSUE THREAD

**Issue by aerler** [UofTCoders/studyGroup#16]
This issue is mainly to gauge interest in geoscience topics, especially geographic information processing, cartography, certain file formats and the like.

Maybe everyone interested in this area can post what they would be interested in and what they are working on, and everyone else can just unsubscribe from this issue.

**Comment by rfajber** [comment]
Hello everyone, 

I am working on running and interpreting results from an intermediate climate model (full atmospheric dynamics, not much else). The model is in Fortran, but I do most of my analysis on netCDF work with command-line tools (CDO and NCO) and Python. 

I would be really interested in someone doing a cartography workshop talking about different projections and how they are calculate, this is an old interest of mine. I am also really interested in the design and numerics of building simple models, quite often you can make reasonably complex models from already existing tools as long as your are not interested in optimizing for performance.

**Comment by QuLogic** [comment]
@rfajber Have you seen [cartopy](http://scitools.org.uk/cartopy/) and [iris](http://scitools.org.uk/iris/)?

**Comment by aerler** [comment]
I am aware of these packages, although I am mainly using basemap and GDAL, which are a bit older, I guess. My impression was, though, that cartopy is limited to plotting and does not do general regridding or rasterization etc.
And for plotting so far I found basemap sufficient.

**Comment by rfajber** [comment]
I also use basemap, since most of what I have to do for my research are really simple polar projection plots. I might take a look at cartopy just for general interest.

@QuLogic have you used iris in the past? How fast is it to load and unload large arrays? I usually find that my Python code is _much_ slower than CDO and NCO for many simple tasks on very large files, simply because the i/o is so slow in Python.

**Comment by aerler** [comment]
I've also wondered about the performance of Iris and Cartopy compared to Python-NetCDF4 and Basemap... does anyone know?

I recently came across this interesting project: https://github.com/xray/xray
It basically provides Pandas functionality for multidimensional arrays. I've implemented something similar myself (https://github.com/aerler/GeoPy - also does regridding and statistics), but this is probably a more generic implementation and under active development - probably the way to go, if you are just starting out.

Related to this, there is this website, which might have interesting resources: http://pydata.org/ (I've heard it mentioned and xray links to it, but I haven't really looked at it in any detail.)

**Comment by QuLogic** [comment]
Well, Iris is based on the NetCDF4 libraries, so one hopes it's not too bad, at least as far as I/O. Actually, Iris uses deferred loading, so it reads only the shapes and coordinates until you need the full data. It's possible it could be faster in that way. I recall a benchmark reading several tens of GBs, but I can't find it at the moment.

Cartopy and Basemap do much the same thing with the same underlying libraries, so they are roughly equivalent in speed. Cartopy is more flexible and has a nicer API, but there are some bugs since it's newer. On the other hand, Basemap gets verry little development.

**Comment by QuLogic** [comment]
xray does look pretty nice, but I've not had much exposure to it. PyData has lots of conference & training videos that are pretty interesting. Also, the [SciPy conference](http://scipy2015.scipy.org/ehome/115969/297898/) from a couple weeks ago.

**Comment by aerler** [comment]
Cartopy and Basemap and Iris and Python-NetCDF4 use the same underlying libraries, yes. And Python-NetCDF4 also uses deferred loading in the same way. 
(Actually lazy-array is pretty cool in this context, but it does not support NetCDF/HDF5 at the moment.)
But for some reason Python-NetCDF4 still manages to be considerably slower than C or Fortran code that links to the libraries directly (I've been told by many people), even if tasks are completely I/O limited and array operations are very simple.

**Comment by QuLogic** [comment]
The usual question is, are they writing Python, or are they writing Python that looks like C/Fortran... I've seen a factor of 3-4 speedup for some converted-from-Java Python (lots of objects) and a factor of 5 for some converted-from-Fortran Python when converting them to proper Python. I'm not saying you'd get the same speed as C/Fortran, but you'd at least be in the same order-of-magnitude.

To get any faster than that, you'd have to move to something like Cython (which I forgot to mention Cartopy uses), but generally you can iterate on Python fast enough that learning it is not worth it (but that's not always the case!)

**Comment by aerler** [comment]
I've finally had a look at Cartopy; it appears to me that it is far superior to Basemap, especially when it comes to flow/vector plots. But I'm having a problem with the axes and projections: how do you specify the projection in subplots? I always get the error that 'projection' is an unknown keyword... It also seems that these GeoAxes interfere with some of my own Axes derivatives...

**Comment by dchandan** [comment]
Python-netCDF4 also uses cython. Iris I believe is mostly python.

**Comment by QuLogic** [comment]
@aerler Do you mean like in [this example](http://scitools.org.uk/cartopy/docs/latest/examples/regridding_arrows.html)?
