### ISSUE TITLE
looking for help importing libraries in python and using self

### ISSUE THREAD

**Issue by ralle123** [UofTCoders/studyGroup#165]
have a setup that calls the following import myfile2 as a2
Then I know that if I go for example a2.name_def I will be calling a def within the myfile2 file,  needed somebody to explain a couple of minutes over google hangout or over a cup of coffee how to get it going. I am also trying to get something working with self and I am a little confused getting started

Thanks =)

**Comment by linamnt** [comment]
Hi @ralle123 we're having a co-working session this Thursday (6pm at Mcclennan Physics room 408) which would be the perfect time to get some help on these things, so if you can make it, it might be quite helpful!
