### ISSUE TITLE
need help with some math problems

### ISSUE THREAD

**Issue by ralle123** [UofTCoders/studyGroup#166]
I am taking a class related to algorithms and computational mathematics and wanted to see if anybody in the group knew of any contacts or a group I could reach out to and get help help understanding some math problems related with mathematical inductions

Thanks,

**Comment by lwjohnst86** [comment]
Hi @ralle123 I'm not sure we are the best group to find out about problems like that. I'm not aware of anyone in math or CS coming to our sessions. You might want to check with the math and CS departments. You would probably have better luck.
