### ISSUE TITLE
Bash tutorial

### ISSUE THREAD

**Issue by nquesada** [UofTCoders/studyGroup#177]
Hello, I was curious about what will be covered in tomorrow's Bash tutorial? How introductory it is? Will you be going through ls and cd and all that or will you also include looping and variables etc...

**Comment by linamnt** [comment]
perhaps @jladan can answer?

**Comment by mbonsma** [comment]
@nquesada, here's what John's got for the lesson material: https://github.com/UofTCoders/studyGroup/pull/176/files

**Comment by jladan** [comment]
That's a good question! I haven't finished everything, but it is more on the introductory side.

An approximate outline:
- what is a cli
- command syntax
- pipes
- (environment) variables
- for loops (especially for each file kind of loop)

I'm not sure how far we can get in the time.

**Comment by jladan** [comment]
Oh, and common commands, of course.

**Comment by QuLogic** [comment]
Lesson's been presented, so I assume this can be closed.
