### ISSUE TITLE
Suggestions for new header image for website

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#186]
Is there a more representative image we could use on the background of the [website](https://uoftcoders.github.io/)? Comments or links to suggestions welcome.

**Comment by lcoome** [comment]
I have a bunch of shutterstock licenses I got for an unrelated reason. I'm down to use one of them up on a new background image. Let's look during the hack session.

________________________________

**Comment by mbonsma** [comment]
[![image](https://cloud.githubusercontent.com/assets/5651370/21026401/5ce75dcc-bd5a-11e6-8266-21b5764d2e99.png)]((https://www.shutterstock.com/pic-346738424/stock-photo-decorative-antique-edison-style-light-bulbs-against-brick-wall-background.html?src=BiCLj9IHSBWJAIxnauWtTQ-1-1))

[![image](https://cloud.githubusercontent.com/assets/5651370/21026475/c31fb314-bd5a-11e6-8b00-375785fafea7.png)](https://www.shutterstock.com/pic-414043981/stock-photo-sideview-of-office-desktop-with-blank-laptop-and-various-office-tools-on-blurry-moscow-city-background.html?src=BiCLj9IHSBWJAIxnauWtTQ-1-28)

[![image](https://cloud.githubusercontent.com/assets/5651370/21026504/eb582348-bd5a-11e6-91ae-5e79bc8e4d78.png)](https://www.shutterstock.com/pic-374648041/stock-photo-office-workplace-with-laptop-on-wood-table-against-the-windows.html?src=BiCLj9IHSBWJAIxnauWtTQ-1-2)

**Comment by mbonsma** [comment]
[![image](https://cloud.githubusercontent.com/assets/5651370/21026570/3e82f520-bd5b-11e6-83f8-93792292a949.png)](https://www.shutterstock.com/pic-340152863/stock-photo-laptop-with-blank-screen-on-table.html?src=BiCLj9IHSBWJAIxnauWtTQ-1-22)

[![image](https://cloud.githubusercontent.com/assets/5651370/21026619/763b4a4e-bd5b-11e6-9fa4-7a33667b70ad.png)](https://www.shutterstock.com/pic-387314050/stock-photo-view-from-the-the-top-of-the-workplace-in-style-with-matte-instagram-filter.html?src=BiCLj9IHSBWJAIxnauWtTQ-2-38)

[![image](https://cloud.githubusercontent.com/assets/5651370/21026648/9e71bd04-bd5b-11e6-8f18-b8cb33f4c52a.png)](https://www.shutterstock.com/pic-319404674/stock-photo-responsive-design-mockup.html?src=BiCLj9IHSBWJAIxnauWtTQ-2-34)

**Comment by lcoome** [comment]
https://www.shutterstock.com/lightboxes/53027193?verification_code=7d9d5779acb3c8a674a5d68f43ba726d



Shutterstock light box

________________________________
