### ISSUE TITLE
Add `r`, `python`, `misc` categories to lessons

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/studyGroup#188]
This will allow us to split the lessons by language, to organize it more.

Maybe even add 'beginner' etc to the categories to organization/list by experience level.

**Comment by linamnt** [comment]
Perhaps we can have a list of tags (Python, R, Beginner, etc.) and then a main page listing all the tags and sort the individual tag pages using the metadata of a lesson

**Comment by linamnt** [comment]
It would look like:

### Level:
- Beginner
- Intermediate
- Advanced

### Language:
- Python
- Misc
- Git
- R

(editted to include more sections)

with each listing linking to a site with relevant lesson.md titles

**Comment by aays** [comment]
@linamnt I could try and take a stab at this!

**Comment by lwjohnst86** [comment]
So like:

- r
- python
- git
- misc

And for experience level:
- beginner
- intermediate
- advanced

(As you had up there)

**Comment by lwjohnst86** [comment]
It would look like this in each `lesson.md` file:

```
---
title: ...
... (other fields) ...
tags:
  - r
  - beginner
---
````

**Comment by linamnt** [comment]
will change lol

**Comment by lwjohnst86** [comment]
See #213 #215 #216 #219
