### ISSUE TITLE
Clean up unnecessary files in the website.

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/studyGroup#189]

**Comment by mbonsma** [comment]
@lwjohnst86, any examples of which files you mean? I can look at this.

**Comment by linamnt** [comment]
started by deleting old constitution files #208

**Comment by mbonsma** [comment]
Moving outreach email file to council repo

**Comment by linamnt** [comment]
I can move this: https://github.com/UofTCoders/studyGroup/blob/gh-pages/admin/SWC_cover_letter.txt
to council as well?

**Comment by linamnt** [comment]
see #211

**Comment by QuLogic** [comment]
I think we did most of this at the hackathon.
