### ISSUE TITLE
"Want to be notified of upcoming events" should link to the "Events" repo

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#190]
On the website under [Events](https://uoftcoders.github.io/studyGroup/#portfolio), if you click the **GitHub** link below **WANT TO BE NOTIFIED OF OUR UPCOMING EVENTS?** it takes you to the [studyGroup](https://github.com/UofTCoders/studyGroup) repo. Instead it should take you to the [Events](https://github.com/UofTCoders/Events) repo.

**Comment by QuLogic** [comment]
@joelostblom is working on this; #196.
