### ISSUE TITLE
Create new repo with only R lessons to make generating them easier?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/studyGroup#191]
So we can also use travis to generate the site?

**Comment by mbonsma** [comment]
What does this mean? Travis to generate the whole site?

**Comment by lwjohnst86** [comment]
Yes! So only need to include the `Rmd` files and not the `html` files. Thoughts? Will this make things more complicated?

**Comment by QuLogic** [comment]
I guess it depends on how complicated we want things to get? Especially if it means more work to run locally.

**Comment by lwjohnst86** [comment]
Thankfully there isn't more work to run locally. Rstudio now has a builtin ability to create websites. So all you have to do is `Ctrl-Shift-B` in Rstudio, check the files look good and that's it! Then push the changes of the `Rmd` files, and travis creates the website! :smile:

**Comment by QuLogic** [comment]
But that means we need Rstudio too?

**Comment by lwjohnst86** [comment]
No, just the package `rmarkdown` using the command `render_site()`

**Comment by lwjohnst86** [comment]
Closing this as it isn't important or necessary right now.
