### ISSUE TITLE
Installation instructions for languages page?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/studyGroup#194]
Put this somewhere on the website so that issues and lessons can link to it.
Thoughts?

**Comment by joelostblom** [comment]
I can write a brief how-to on Python and R through conda.

**Comment by mbonsma** [comment]
:+1: for conda. Works on most operating systems, as far as I know.

**Comment by QuLogic** [comment]
Software Carpentry might have some reference on these.

**Comment by mbonsma** [comment]
Where are we going to put this on the website?

**Comment by mbonsma** [comment]
Something like this should work for Git: https://swcarpentry.github.io/workshop-template/#git

**Comment by joelostblom** [comment]
Not sure, I'm writing a brief guide for conda now. Will post here soon.

**Comment by mbonsma** [comment]
LaTeX: [TeXLive (Linux)](http://www.tug.org/texlive/), [MacTeX (Mac)](http://www.tug.org/mactex/), [MikTeX (Windows)](https://miktex.org/), or [TexMaker (any platform)](http://www.xm1math.net/texmaker/)

**Comment by joelostblom** [comment]
Ok, I added a draft of setup instructions for conda. I need to run now, so feel free to edit however and put it in a good location.
