### ISSUE TITLE
Remove Wiki, put some of it on the site?

### ISSUE THREAD

**Issue by lwjohnst86** [UofTCoders/studyGroup#195]
We've migrated a lot of the functionality of the wiki to the website. Let's remove it. Thoughts?

**Comment by mbonsma** [comment]
I think all we need to keep from the wiki is [contributing a lesson](https://github.com/UofTCoders/studyGroup/wiki/Contributing-a-lesson). The [notes from Hacky Hour 1](https://github.com/UofTCoders/studyGroup/wiki/Notes-from-Hacky-Hour-1) we could put in the meeting notes folder of the council repo, and I think the rest we can scrap.

**Comment by mbonsma** [comment]
@linamnt pointed out that contributing is [already on the website](https://uoftcoders.github.io/studyGroup/CONTRIBUTING/). So we're good to go, I'll just copy the hacky hour notes to the council repo.

**Comment by mbonsma** [comment]
Done in this [PR](https://github.com/UofTCoders/council/pull/53) in the council repo.

**Comment by lwjohnst86** [comment]
See https://github.com/UofTCoders/council/pull/53
