### ISSUE TITLE
Rename website sections to make sense

### ISSUE THREAD

**Issue by QuLogic** [UofTCoders/studyGroup#198]
Website sections were dictated by the original theme; portfolios, clients, etc. We should name them for what they actually are.

**Comment by QuLogic** [comment]
I think this is pretty straight-forward; you just have to be careful to update all the places: the CSS, the Jekyll includes, etc.

**Comment by mbonsma** [comment]
@QuLogic, do you know all the places to check off the top of your head? If we can list them here that would be helpful for whoever does this.

**Comment by linamnt** [comment]
- CSS class tags in _includes/css/agency.css.
- _includes .html files
- _layouts/defaults.html

I think that's it but please add if I missed something

Also should this be done last after we change the files,so they don't lead to merge problems?

**Comment by QuLogic** [comment]
I discussed with @joelostblom what to do and he's going to start working on it.
