### ISSUE TITLE
We have a chat room!

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#2]
We can use Gitter to informally chat whenever, or during events. ~~I made us a [UofTstudyGroup](https://gitter.im/mbonsma/UofTstudyGroup?utm_source=share-link&utm_medium=link&utm_campaign=share-link) chat room.~~ Everyone is welcome, all the time. 

Please use the new [lobby room](https://gitter.im/UofTCoders/Lobby).

**Comment by lwjohnst86** [comment]
I know this is old and not many people I feel use the chat room, but is it possible to rename the UofT study group to UofTCoders?

**Comment by QuLogic** [comment]
We should open it under the org, but then we'd lose the history, I think. I don't know if there's a way to migrate it.

**Comment by tkivisik** [comment]
Would the loss of history be a big deal as there isn't much history there (there's talk only during the summer and a bit in May this year)? UofTCoders would be nice.
Cheers

**Comment by mbonsma** [comment]
We could open a new one entirely, then the old one would still exist if someone still wanted to go looking for it. I agree with Taavi that since not much happened in the chat, it's okay to start again.

**Comment by QuLogic** [comment]
The [Lobby](https://gitter.im/UofTCoders/Lobby) is now open.
