### ISSUE TITLE
Mobile Version + Title/Home Link glitches?

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#222]
1. The mobile version doesn't span the width of the screen (see below) though it used to:
![mobile-glitch](https://cloud.githubusercontent.com/assets/10761918/21053623/42eaaf98-bdf8-11e6-8bb0-50db5744bbdc.png)
2. The title doesn't link back to the home page on the lesson content page? 

Edit: I see that the University of Toronto Coders links to #page-top, so I guess that's fine as we add more lessons, might be useful.

**Comment by mbonsma** [comment]
I was also noticing number 2, I think if we keep its behaviour as taking you to the top of the page, it might be worth adding a **home** button. Thoughts?

**Comment by linamnt** [comment]
I think replacing it to home might be better because people can always go to the top of lessons by reloading the page? or is that my non-ux side talking?

**Comment by QuLogic** [comment]
I can't reproduce the problem with the sizing; maybe it's browser-specific. The logo is actually a link to the home page.

**Comment by ralle123** [comment]
Do you guys need help with your web layout?

Let me know, I would be happy to help =)

Raul

________________________________
