### ISSUE TITLE
Software Carpentry Python/Unix Shell/Git Workshop - Call for Helpers/Attendees

### ISSUE THREAD

**Issue by lcoome** [UofTCoders/studyGroup#229]
U of T Coders is hosting a hands-on two-day Software Carpentry workshop 
covering core small research team skills. Through short tutorials and 
practical exercises, attendees will learn:

- Automating tasks with the Unix Shell
- Version control with Git
- Programming with Python

**You don't need to have any previous knowledge of the tools that will be 
presented at the workshop.**

When: February 3-4, 9am - 4pm
Where: Claude T. Bissell Building, 140 St. George Street, Room BL 538
Cost: $20

[Website](https://uoftcoders.github.io/2017-02-03-utoronto/)
[Facebook event](https://www.facebook.com/events/248221502280437/)
[Registration page](https://www.eventbrite.ca/e/software-carpentry-and-u-of-t-coders-gitunix-shellpython-tickets-30865556711)

**IF YOU WANT TO COME AS A HELPER, PLEASE E-MAIL ME AT lindsay.coome@mail.utoronto.ca AND LET ME KNOW WHICH DAYS/SUBJECTS YOU ARE AVAILABLE FOR :)** 

Note: Helpers attend for free, obviously!

**Comment by aays** [comment]
@lcoome I'd be happy to help! Emailed.

**Comment by QuLogic** [comment]
Thanks to all the helpers who came out last week.
