### ISSUE TITLE
Lesson content links are broken on website

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#231]
Most of the lesson.md files in the [lessons](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons) folder still have the old structure in the links - i.e. if you click on the lesson content link on the [Intro to Python](https://uoftcoders.github.io/studyGroup/lessons/python/intro/lesson/) page it 404s.

**Comment by mbonsma** [comment]
I'll fix it in the intro python lesson, but I haven't fixed any others.

**Comment by lwjohnst86** [comment]
Ooo, good call, I forgot about that.
