### ISSUE TITLE
Winter/Spring Sessions - Call for instructors + Tentative Schedule

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#234]
## Session Schedule

Here is the tentative schedule for the winter/spring sessions. If you're interested in leading any of these, please reply here or email uoftcoders@gmail.com. Note you do not need to be an expert to teach! If the dates for the lesson you want to teach don't work for you, let us know and we'll fiddle things around so it works! 

For those unfamiliar, lightning demos are short demos (5-10min max) on the topic for that session. No code along is necessary, just show us what you've done or a quick overview of a tool or package. These are great if you're not quite ready to teach a full session but want to give presenting a try!

- Code Review Session - Feb 1
    - (lesson involves 15 min discussion on code review principles, and the rest of the lesson will be pairs/groups reviewing actual code from other members) 
- Coworking Session - Feb 8
- [ggplot2 in R](https://uoftcoders.github.io/studyGroup/lessons/r/ggplot2/lesson/) - Feb 15 - Lindsay Coome
- Collaborating with Github - Feb 22 - Serena Jeblee
- [Opening up your data](https://github.com/mozillascience/open-data-training) - March 1 - Derek Howard
    - This can either be a discussion about reasons why you can and should open up your data along with common challenges, or a presentation about how you can go about doing so (principles about good open data) 
- Lightning Demo: Data Visualization - March 8
- [ Intro SQL](https://uoftcoders.github.io/studyGroup/lessons/misc/sql-intro/lesson/) - March 15 - Brian Sutherland
- Coworking Session - March 22
- Intermediate Topics in R - March 29 - Luke Johnston
- Intermediate Topics in Python - April 5 - Ahmed Hasan
- Lightning Demo: Academic Workflows  - April 12
    - what tools and programs do you use to analyze, visualize and communicate your data?
- Coworking Session - April 19
- Hacky Hour Social @ GSU Pub - April 26 (+Elections?)
- [Careers Outside Academia Panel](https://uoftcoders.github.io/studyGroup/lessons/misc/careers-outside-academia/lesson/) - May 3
    - Are you or do you know someone who started in research but took opportunities outside academia? This session will discuss different paths after a graduate research program.
- Lightning Demos: Working with Very Large Datasets - May 10
- Coworking Session - May 17

**Comment by lcoome** [comment]
Dibs on ggplot2!

**Comment by linamnt** [comment]
Thanks @lcoome! the date works for you?

**Comment by lcoome** [comment]
Yes!
________________________________

**Comment by lwjohnst86** [comment]
I can do the intermediate topics in R and one of the demos for Academic workflows. Both dates are fine by me.

**Comment by linamnt** [comment]
I'll take a stab at presenting the intro and moderating the groups for code review!

**Comment by linamnt** [comment]
Hi Everyone, We're still looking for instructors for Collaborative Coding in Github (feb 22), and Opening up Your Data (march 1). If you or someone you know would like to teach one of these lessons, let us know!

**Comment by derekhoward** [comment]
I can take on the "Opening up Your Data"  session on March 1st.

Also, I've found [this git book](https://www.practicereproducibleresearch.org/) which could be relevant for the academic workflows. I think there is some good background and a bunch of cool example case studies.

**Comment by joelostblom** [comment]
I could do a couple of lightning demos: Bokeh for Data Visualization, and Zsh and tmux for Academic Workflows.

I might also be able to do a demo on Datashader for the third session, but that will depend on how much I will have worked with the package before then, so I will have to get back on that later this spring.

**Comment by sjeblee** [comment]
If you're still looking for someone for the github session, I can teach or help out!

**Comment by linamnt** [comment]
@sjeblee Yes that would be great if you could teach that lesson! Do you mind shooting uoftcoders@gmail.com an email so we can coordinate?

Thanks!
