### ISSUE TITLE
microarray analysis help / R / Big-ish data

### ISSUE THREAD

**Issue by northmi1** [UofTCoders/studyGroup#237]
I have data from Illumina EPIC arrays, which are the next version of the 450k array with over 1 million DNA methylation sites. Pipelines exist to analyze this data, and I have a little bit of experience in R, but I am afraid to try to open the arrays in RStudio on my laptop because I think working with them all and manipulating/comparing them between groups will be too big and my laptop will explode. So I am looking for options on the U of T campus and a paid tutor or a collaborator to help me get started working with the data. Any thoughts/takers? 

[humanmethylationepic-data-sheet-1070-2015-008.pdf](https://github.com/UofTCoders/studyGroup/files/752488/humanmethylationepic-data-sheet-1070-2015-008.pdf)

[https://bioconductor.org/packages/release/bioc/html/ChAMP.html](url)

**Comment by mbonsma** [comment]
Hey @northmi1, that sounds like a really cool dataset! I don't have much experience in R myself but there are a bunch of people here who do (@lwjohnst86, @lcoome, @thesarahmeister, etc.) - would you be interested in dropping by at a coworking session to play around with the data a bit? (The next coworking session is this coming [Wednesday](https://github.com/UofTCoders/Events/issues/85)).

**Comment by northmi1** [comment]
That sounds great, I will be there!
