### ISSUE TITLE
Create Organization logo

### ISSUE THREAD

**Issue by QuLogic** [UofTCoders/studyGroup#24]
Pulled out of #3 for separate discussion.

@QuLogic

> One thing we need is an org logo. UT logo or crest?

@mbonsma

> Are we allowed to use a UofT logo? Any graphic designers in the house want to make us a sweet logo?
> 
> We could also probably use a Mozilla Science Lab logo.

@QuLogic

> Maybe @atavasoli or @lwjohnst86 have some input on club rules about logos.
> 
> Or, since I'm lazy, how about [this](https://openclipart.org/detail/221200/teaching-code) (public domain; needs a little tweaking to fit)?

@lwjohnst86

> @mbonsma once we become recognized by UofT, we can for sure use their logo! (I think they would actually encourage it for publicity... ie fundraising). But I agree that a UofT Coders specific logo would be cool! And a good branding strategy too!
> 
> If there are no graphic designers here, I've done some graphics for some of my stuff, so I could take a stab at editing the clip @QuLogic suggested.

@mbonsma

> Cool! I totally don't mind using a UofT logo once we're recognized, but it would be fun to have our own.

**Comment by lwjohnst86** [comment]
Haven't had a chance to get to this, but hoping to fiddle with something by next week.

**Comment by QuLogic** [comment]
No rush; we aren't recognized yet anyway.

**Comment by linamnt** [comment]
I was procrastinating this weekend which led to this:
![uoftcoders_logo](https://cloud.githubusercontent.com/assets/10761918/9445742/9ff007ea-4a5b-11e5-8231-313138c00ea7.png)
Not sure if it captures what we want it to capture, but thought I might as well share.

**Comment by lwjohnst86** [comment]
Very nice, it looks very professional and clean. However, a chemistry vial and electric circuits may not reflect what we do. What if the circuit background were instead like a bunch of (slightly faded) code snippets from different languages? Overlapping one another or something..? And the vial maybe like a laptop or monitor or hard drive or something..? Though the vial is very useful at representing (at least a portion of) science. Another possibility would be a microscope, or like a telescope. 

Just my two cents! Great start regardless!! 😊

On 24 August, 2015 12:29:48 PM EDT, Lina Tran notifications@github.com wrote:

> I was procrastinating this weekend which led to this:
> ![uoftcoders_logo](https://cloud.githubusercontent.com/assets/10761918/9445742/9ff007ea-4a5b-11e5-8231-313138c00ea7.png)
> Not sure if it captures what we want it to capture, but thought I might
> as well share. 
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/UofTCoders/studyGroup/issues/24#issuecomment-134290619

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by linamnt** [comment]
Oh, I really like the idea of the code snippets! I wanted to convey the
'computer' aspect and wasn't sure how to, hence, circuit board...

And I agree, the flask biases it towards only a subset of the fields we
represent, but on the other hand, it is simple and I couldn't really think
of an all-encompassing, universal "science" logo. I can definitely try the
different sciencey icons that you suggested though and we can see how they
look :)

On Mon, Aug 24, 2015 at 12:49 PM, Luke W Johnston notifications@github.com
wrote:

> Very nice, it looks very professional and clean. However, a chemistry vial
> and electric circuits may not reflect what we do. What if the circuit
> background were instead like a bunch of (slightly faded) code snippets from
> different languages? Overlapping one another or something..? And the vial
> maybe like a laptop or monitor or hard drive or something..? Though the
> vial is very useful at representing (at least a portion of) science.
> Another possibility would be a microscope, or like a telescope.
> 
> Just my two cents! Great start regardless!! 😊
> 
> On 24 August, 2015 12:29:48 PM EDT, Lina Tran notifications@github.com
> wrote:
> 
> > I was procrastinating this weekend which led to this:
> > ![uoftcoders_logo](https://cloud.githubusercontent.com/assets/10761918/9445742/9ff007ea-4a5b-11e5-8231-313138c00ea7.png)
> > Not sure if it captures what we want it to capture, but thought I might
> > as well share.
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/UofTCoders/studyGroup/issues/24#issuecomment-134290619
> 
> ## 
> 
> Sent from my Android device with K-9 Mail. Please excuse my brevity.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/24#issuecomment-134297063
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by QuLogic** [comment]
It looks pretty good, though for some reason it looks "familiar". I think maybe because it has the same colour aesthetic as [this page](https://github.com/showcases/text-editors), but I can't quite place it. Otherwise, I agree with @lwjohnst86.

Also, we'd eventually need something that fits in 48x48px neatly (for the logo to the left here), though sometimes it's shown at 100x100px or even 20x20px. Something simple like this tends to scale down easier.

**Comment by mbonsma** [comment]
Cool! @linamnt, I love the {brackets}. I agree that the chemistry vial is a good generic science symbol, but I think it might be good to go even more general - we have some humanities people too. What about something like a light bulb, or something that symbolizes ideas in general?

**Comment by linamnt** [comment]
![uoftcoders_lightbulb](https://cloud.githubusercontent.com/assets/10761918/9772242/f139779e-5708-11e5-9df7-6df2e0695c92.png)
![uoftcoders_logo_scope](https://cloud.githubusercontent.com/assets/10761918/9772247/f542b468-5708-11e5-881e-816fde386b15.png)

Here are two versions with the suggestions!

**Comment by lwjohnst86** [comment]
Ooo I like!! Both are great, but I especially like the lightblub one! Excellent job!

**Comment by mbonsma** [comment]
I agree! My vote's for lighbulb. Very nice!

**Comment by jayemme** [comment]
The lightbulb one is great!

On Sep 9, 2015, at 3:40 PM, Lina Tran <notifications@github.com<mailto:notifications@github.com>> wrote:

[uoftcoders_lightbulb]https://cloud.githubusercontent.com/assets/10761918/9772242/f139779e-5708-11e5-9df7-6df2e0695c92.png
[uoftcoders_logo_scope]https://cloud.githubusercontent.com/assets/10761918/9772247/f542b468-5708-11e5-881e-816fde386b15.png

Here are two versions with the suggestions!

**Comment by lwjohnst86** [comment]
@linamnt would you be able submit a PR with the image (maybe both?) into the studyGroup repo (under the `img` directory)? Then we can include it into the website + on the GitHub account! :smiley: 

If everyone is in agreement that is!

**Comment by QuLogic** [comment]
We need 100x100 for the GitHub organization and probably something to fit in the top left of the bar here (about 60x60):
![screen shot 2015-09-13 at 16 16 53](https://cloud.githubusercontent.com/assets/302469/9838762/20557bea-5a33-11e5-8e79-2f4768e987bc.png)
You might want to tweak the colours or try inverting it to go on that dark background.

Also, in the spirit of open source, don't forget to include the source files.

**Comment by linamnt** [comment]
Sorry for taking so long but I've made an icon-sized logo as well as a dark version for the website and added it to a pull request. I originally made one with the constitution changes so I don't know how to dissociate the two but it's there now!

**Comment by lwjohnst86** [comment]
See PR #47
