### ISSUE TITLE
Brain Hack Toronto

### ISSUE THREAD

**Issue by ricardoharripaul** [UofTCoders/studyGroup#240]
Hi Everyone, 

We are having a BrainHack Toronto hosted by CAMH.  Attached is a flyer with all the relevant information for signing up and coming over.  Hope to see you there.

[BrainHackToronto2017.pdf](https://github.com/UofTCoders/studyGroup/files/764016/BrainHackToronto2017.pdf)

**Comment by lcoome** [comment]
Is neuroimaging knowledge/experience necessary?

________________________________

**Comment by ricardoharripaul** [comment]
Neuroimaging knowledge is not necessary.  We are encouraging other disciplines to attend and and bring their expertise.  We have some workshops to bring people up to speed on neuroimaging already planned.

**Comment by jdpigeon** [comment]
I'm in!

**Comment by ricardoharripaul** [comment]
Hi, 

Just a reminder.  We are anticipating a rush to sign up so if you have not signed up as yet please do ASAP.

Cheers, 

Ricardo
