### ISSUE TITLE
Videos link or indicators on lessons page

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#246]
Might be cool if we had a little indicator beside lesson name, eg a camera icon, to indicate to people if there is video available for the lesson? 
Not sure if this is me getting feature-happy heh...

Or more simply, we could provide a link on our lessons page to our youtube channel if people just wanna scroll through.

**Comment by mbonsma** [comment]
I definitely think a link to the youtube channel on the lessons page would be great. In the past we've linked the video in the lesson file, but we often get behind on that, so this way people could find it easily.

**Comment by mbonsma** [comment]
Relatedly: could we have a link to the [lessons folder](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons) itself on the lesson page of the website? Since not all lessons are displayed with working links all the time, that way people can find the source files easily.

**Comment by linamnt** [comment]
That's a good suggestion too, for sure while we have the broken link issue

**Comment by QuLogic** [comment]
If we move the video link into the metadata instead of the bullet points, we can have that link autogenerated on the lesson listing.

**Comment by lwjohnst86** [comment]
I like this idea a lot but I think it will take too much time maintaining, unless there is a way to automate this (putting each youtube link in the metadata isn't terribly automated). Closing for now.
