### ISSUE TITLE
Events calendar for planning sessions

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#25]
@lannajin suggested a calendar that people can edit and suggest dates for sessions they'll be leading. Should it be a public Google calendar, or something built directly into the Github pages structure?

**Comment by QuLogic** [comment]
GitHub Pages are static, so you'd have to use PRs and such. But that's probably more work than just opening an issue in the [Events repo](https://github.com/UofTCoders/Events).

**Comment by katieannemills** [comment]
@ttimbers and the SFU group are using a google calendar to list events as their 'low traffic' option for people who don't want GitHub notifications; I'm currently contemplating pulling that feature upstream and making it standard; should I consider this another vote in that direction?

**Comment by mbonsma** [comment]
I think you can count this as +1 for the calendar!

**Comment by ricardoharripaul** [comment]
I was expecting to present this Thursday.  I can present this Thursday on Matplotlib if no one has any objections.  I would like to know so I can get all the code together.

**Comment by lwjohnst86** [comment]
With https://github.com/UofTCoders/studyGroup/pull/34 now merged, I'll close this.
