### ISSUE TITLE
Mozilla Global Sprint, June 1-2

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#269]
Mozilla Science Lab is holding their **annual [Global Sprint](https://mozilla.github.io/global-sprint/) on June 1 and 2**. This is a super fun two-day event where people from around the world gather virtually and at local sites to work on open projects. You don't have to commit to the whole thing, people are welcome to come in and out as their schedule permits. 

The [Mozilla Toronto office](https://ti.to/Mozilla/global-sprint-toronto) will be a site, and it would be great to gather some UofT Coders people here in Toronto! What do people think about proposing a group project to work on a the sprint? I know @linamnt has some ideas about machine learning and fake news, for example. 

Here are some options for participating in the sprint:
1. Sign up as individual participants [here](http://mozilla.github.io/global-sprint/participants/) (which we should do anyway even if we bring a project) and work on [other participating projects](https://github.com/mozilla/global-sprint/issues). 
2. Create a project to work on at the sprint! Project sign-up is [here](http://mozilla.github.io/global-sprint/project-lead/). If you have a project you want to individually bring as well, definitely sign up!
3. [Host a site](https://mozilla.github.io/global-sprint/site-hosts/) - we could definitely consider this, especially as an outreach tool for the group, but I also do like going to the Mozilla office...

**Comment by joelostblom** [comment]
So many [cool featured projects!](https://mozilla.github.io/global-sprint/projects/) I especially like ones about embryogenesis, solar power, and open funding, but if there is a few of us who wants to go, I am down to join one project all together, I would probably enjoy working on any of the ones listed on their featured page. And I am also down to work on a project of our own, but I don't know how much time I would be able to contribute in setting that up.

I signed up for the Mozilla Office location in downtown! I have never been at the Mozilla headquarters, exciting!

**Comment by mbonsma** [comment]
I'll be working on my project, [phageParser](https://github.com/phageParser/phageParser)!

Mozilla Toronto is officially a site, I'll update the original comment with that.

**Comment by joelostblom** [comment]
Approximately what time during the day is the global sprint? A friend of mine asked me for moving help on the afternoon of June 2nd, so I am trying to figure out if that is realistic.

**Comment by mbonsma** [comment]
It's 9-5 ish at each site, so various groups come on and offline as the timezones change. You can also duck out for part and come back later, or come to only part of the sprint.

**Comment by joelostblom** [comment]
Thanks! I will probably just leave a couple of hours earlier or so on the 2nd then.

**Comment by jdpigeon** [comment]
I'll be there to work on [EEG 101](https://github.com/NeuroTechX/eeg-101)!
