### ISSUE TITLE
Spring/Summer 2017 Tentative Schedule (Call for Instructors)

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#270]
Hi Everyone,

Here is the tentative schedule for our Spring/Summer sessions. If you'd like to lead one of these sessions, please reply here with the following:

     - Which session you'd like to teach
     - If you're okay with the proposed date
     - If not, what date you'd prefer to teach the lesson

We will get in contact with you thereafter to coordinate. 

**Edit:** For those unfamiliar, lightning demos are short demos (5-10min max) on the topic for that session. No code along is necessary, just show us what you've done or a quick overview of a tool or package. These are great if you're not quite ready to teach a full session but want to give presenting a try!

Those with a (**) indicate lessons requiring an instructor.
- May 24 - HTML/JS/CSS for web development (John, @jladan)
- May 31 - Intro to Bash (Joel, @joelostblom)
- June 7 - Python: SciKit Learn - regression, fitting, machine learning (Nil)
- June 14 - Themed coworking session for unit test, pair programming session
- June 21 - Git: continuous integration and testing  (Luke, @lwjohnst86)
- **June 28 - Data visualization lightning demos
- July 5 - Intermediate SQL (Brian)
- July 12 - Themed coworking for making packages, both R and Python
- July 19 - R: dplyr and magrittr (Ahmed, @aays)
- **July 26 - Python: intro to GPU programming 
- Aug 2 - Collaborating with others using GitHub (Kathy, @chungkky)
- Aug 9 - Coworking Session
- Aug 16 - R: Resampling Techniques (Bootstrapping & Permutation Testing) (Luke, @lwjohnst86)
- Aug 23 - Intro to Docker (John, @jladan)
- Aug 30 - End of Summer, New Term Social

**Comment by joelostblom** [comment]
The Bash intro, teach it, I can.

And could we switch Aug2 and Jul26 (or some other date)? I would like to attend Python GPU programming, but I might be gone Aug 2 already.

**Comment by linamnt** [comment]
Thanks @joelostblom , I've moved the date, but of course depends on availability of instructors :)

**Comment by aays** [comment]
I've a sneaking suspicion @lwjohnst86 might want to take the dplyr and magrittr lesson on the 19th (and could certainly teach it better than I) but if he's busy I wouldn't mind giving it a shot!

**Comment by lwjohnst86** [comment]
@aays you take it! :smile: I can teach the `R: Resampling Techniques` on Aug 16th and if need be the `Git: continuous integration and testing`, though I feel @QuLogic will know more about it and maybe want to teach it?

**Comment by mbonsma** [comment]
Just a note that we also need people to give lightning demos (the June 28 one) even though there's no lead instructor!

**Comment by chungkky** [comment]
Late joining in but I'd be interested in teaching any intro to Bash lessons and Intro to Git and GitHub, Markdown (esp. to humanities and social sciences people).  Can also do Intro to XML/TEI and some 
XPath, XQuery.

**Comment by rallevader** [comment]
Is there a course already created for the "Data visualization lightning demos" or do we need to create it? Is this to be done in python or R? I could volunteer to do it

**Comment by linamnt** [comment]
Hi @rallevader the demos are are short demos (5-10min max) on the topic for that session, so a demo of how you do data viz in your own work. No code along is necessary, just show us what you've done or a quick overview of a tool or package. I've updated the post so others know as well.

Let me know if you have other questions.

**Comment by linamnt** [comment]
We're still looking for instructors for **Intermediate SQL**, and **Python: Intro to GPU Programming**. If you are or know someone who would like to lead these sessions, please let us know at uoftcoders@gmail.com 

You don't need to be an expert to lead lessons, and can definitely use any online tutorials or lessons that are already made as a basis for your lesson, no need to always make up all of your own material!
