### ISSUE TITLE
Summer volunteer opportunities related to wearable devices / neuroscience

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#278]
A friend of mine in high school is looking for summer work or volunteer opportunities at the university. She's interested in neuroscience, data science, wearable devices, and Matlab. Does anyone know of groups or professors she could get in touch with?

**Comment by jdpigeon** [comment]
I definitely have a bunch of projects she might be interested in working on. Want to point her to me? You have my email I think.

I can bring her out to the NeuroTechTO hacknights and put her in touch with some people.
