### ISSUE TITLE
Help Wanted for Search Engine Project

### ISSUE THREAD

**Issue by StefanFernando** [UofTCoders/studyGroup#285]
Hi guys, 

I'm from the business school (Rotman). I'm looking to build a search engine as part of a live venture and was wondering if anyone had the expertise in and would like to help, or know anyone that would be interested. 

Thanks,
Stefan

**Comment by ralle123** [comment]
it all depends on how complex you need it and what languages you have available to work with. If it is something simple you need, you could do something like this http://www.planet-source-code.com/vb/scripts/ShowCode.asp?lngWId=4&txtCodeId=6216 plain HTML and javascript
