### ISSUE TITLE
October 17 meetup for GTA people interested in teaching coding

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#297]
[Greg Wilson](gvwilson) is organizing a meetup for people in the GTA who are interested in teaching coding and other tech skills, both in traditional classrooms and other settings. It will be a chance for people to meet one another, exchange ideas, and make connections. 

The sign-up page is at:

https://teaching-tech-together-toronto-october-2017.eventbrite.com

**Where:** Intelliware Development Inc., 200 Adelaide West
**When:** October 17, 2017, 6:30-9:00 pm

**Comment by chungkky** [comment]
sorry everyone for the short notice.  Just learnt more about this and 
thought it might be of interest. It's later today, and it's free but you 
have to register.

Kathy

-- 
Kathy Chung | Postdoctoral Fellow in Digital Humanities
Records of Early English Drama, University of Toronto
http://reed.utoronto.ca
https://ereed.library.utoronto.ca


-------- Forwarded Message --------
Subject: 	Reminder: IIIF Toronto Showcase, Tues. Oct. 10
Date: 	Tue, 10 Oct 2017 02:09:26 +0000
From: 	Sheila Rabun <srabun@clir.org>



Greetings all,

Thank you for registering to attend the *International Image 
Interoperability Framework (IIIF) Toronto Showcase on _Tuesday, October 
10_*. Event information is available online at 
http://iiif.io/event/2017/toronto-showcase/.

*Location: *

University of Toronto

Robarts Library – Blackburn Room (4^th floor, room 4036)

130 St. George St.

Toronto, ON

*Schedule:*

3:30pm – coffee and registration

4-6pm – Showcase program, discussion, and Q&A (schedule details: 
http://iiif.io/event/2017/toronto-showcase/#schedule)

6-8pm – Reception at the Thomas Fisher Rare Book Library (appetizers, 
beer, and wine will be served)

Please bring your IIIF-related thoughts and questions. I’m looking 
forward to seeing everyone there!

Best,

Sheila

Sheila Rabun

IIIF Community and Communications Officer

International Image Interoperability Framework (IIIF) Consortium

http://iiif.io <http://iiif.io/>

id:image001.png@01D22A5A.CDDAAF90
