### ISSUE TITLE
Create an organization

### ISSUE THREAD

**Issue by QuLogic** [UofTCoders/studyGroup#3]
Eventually you'll graduate, and then it'd be a little weird that this site is under your username. The most difficult part is deciding what name it should be... :wink: (e.g., UofT, UTor, UToronto are all taken).

(I am of course assuming that you will graduate quickly and this study group will last a long time, but obviously that's true, right?)

**Comment by mbonsma** [comment]
I'll probably be around for the next 4-5 years, but ideally this group will outlast me by a long time. I think this is a good idea - do you know how easy it is to migrate the repo to a different username?

**Comment by QuLogic** [comment]
You can create an organization by clicking the + menu at the top right, and you can Transfer ownership in the repo settings. You need to be an admin for both ends to do so. It seems rather painless; the hard part is making sure everyone goes to the new place.

**Comment by mbonsma** [comment]
Sounds good. I made an organization called 'UofTStudyGroup', we can probably change the name if people want. @QuLogic, would you recommend I go ahead and switch the repo to the organization?

**Comment by abbycabs** [comment]
If you switch, make sure you leave a lot of pointers to the new group -- I think ppl are mostly watching this repo :)

**Comment by QuLogic** [comment]
[Almost everything](https://help.github.com/articles/transferring-a-repository/#whats-transferred-with-a-repository) is redirected when you transfer a repository, so I think you wouldn't lose anybody. But it might be a good idea to send out a reminder.

Also, when you transfer, if you rename it to `UofTStudyGroup.github.io`, then you'll get https://UofTStudyGroup.github.io/ instead of the slightly redundant https://UofTStudyGroup.github.io/studyGroup.

**Comment by abbycabs** [comment]
@QuLogic +1

**Comment by QuLogic** [comment]
> if you rename it to UofTStudyGroup.github.io, then you'll get https://UofTStudyGroup.github.io/

You'll have to wait for mozillascience/studyGroup#13 for this to work properly (or just merge it here, but I'd prefer some review first.)

**Comment by mbonsma** [comment]
Sounds good, let's see what the master branch has to say.

**Comment by QuLogic** [comment]
It's now merged upstream and here.

**Comment by mbonsma** [comment]
Successfully implemented! This can be closed.

**Comment by QuLogic** [comment]
One thing we need is an org logo. UT logo or crest?

**Comment by mbonsma** [comment]
Are we allowed to use a UofT logo? Any graphic designers in the house want to make us a sweet logo?

We could also probably use a Mozilla Science Lab logo.

**Comment by QuLogic** [comment]
Maybe @atavasoli or @lwjohnst86 have some input on club rules about logos.

Or, since I'm lazy, how about [this](https://openclipart.org/detail/221200/teaching-code) (public domain; needs a little tweaking to fit)?

**Comment by lwjohnst86** [comment]
@mbonsma once we become recognized by UofT, we can for sure use their logo! (I think they would actually encourage it for publicity... ie fundraising). But I agree that a UofT Coders specific logo would be cool! And a good branding strategy too!

If there are no graphic designers here, I've done some graphics for some of my stuff, so I could take a stab at editing the clip @QuLogic suggested.

**Comment by mbonsma** [comment]
Cool! I totally don't mind using a UofT logo once we're recognized, but it would be fun to have our own.
