### ISSUE TITLE
Add links to lesson content in YouTube video descriptions

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#316]
It would be nice if in the descriptions of our [videos](https://www.youtube.com/channel/UCfGUFz6EG5gBfRt8-du0jaA) there was a link to the [lesson content](https://github.com/UofTCoders/studyGroup/tree/gh-pages/lessons) for that particular session. If you're interested in helping out with this, send an email to uoftcoders@gmail.com so we can give you access to the youtube account.

**Comment by linamnt** [comment]
Went through our catalogue and added any missing lesson content links. The only ones missing are those where the instructor did not send us their content after. I also updated the Streamyard instructions for future videos.
