### ISSUE TITLE
Digital Humanities workshop Dec 11-12 - call for instructors

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#319]
The [Digital Humanities Network](https://www.humanities.utoronto.ca/DH_at_UofT) and Jackman Humanities Institute in collaboration with UofT Coders will be holding a two-day workshop on **Dec 11 and 12** for digital humanities practitioners, and we are looking for instructors! 

The topics are tentatively WordPress, HTML, and Python, with WordPress HTML one day and Python the other day. Instructors can do half-days or an entire day. Send an email to uoftcoders@gmail.com or comment here if you're interested in instructing or helping out for part of the workshop.

**Comment by joelostblom** [comment]
I would like to instruct for one or several of the Python workshops!
Preferably something related to analyses and plotting (pandas / matplotlib
/ seaborn), if we are teaching that. If not, I could do something
introductory instead.

**Comment by chungkky** [comment]
A thought . . .  Do you know who the participants will be? Roughly from which disciplines? Are they people working mainly with text or with info on spreadsheets (strings or numbers?) or with stats? If it's text and you are teaching Python, you might consider how you would apply matplotlib or seaborn in the uses cases. You might take a look at the [Programming Historian](https://programminghistorian.org/lessons/?topic=python) website (a really well respected humanities computing teaching site) and see what they do with Python.

**Comment by mbonsma** [comment]
@chungkky - we don't know precisely which disciplines but it will definitely be humanities people, I know that's not very specific!

**Comment by chungkky** [comment]
@mbonsma -- ok. My suggestion is that since it is humanities people, while graphing and plotting libraries are cool and visually pleasing, it might be more useful for your humanities learners to teach them Python tools for working with text...  At least, be conscious that humanities data is different from science data, numbers may come into it but usually, primary data are not numbers (for historians, maybe census numbers, yes).

**Comment by chungkky** [comment]
I am interested in teaching a lesson on Introductory HTML and Markdown and the general notion of mark up languages.

**Comment by mbonsma** [comment]
@chungkky would you be interested in covering WordPress as well or just HTML / markdown / mark-up?

**Comment by joelostblom** [comment]
Good points @chungky! I am not that familiar with what skills would be the
best to learn for humanities studients. I imagine that basic analytic and
visualization tools are useful for nearly everybody. I can also teach
introductory python and text processing, and how to make wordclouds. If we
want to do more advanced lectures such as NLP, that's something where I do
not have experience (but could potentially learn a bit depending on how
deep we want to go into these topics).

**Comment by mbonsma** [comment]
@dcwalk - do you have thoughts on what should be covered in a day of WordPress / HTML? Or should we be going the Jekyll / GitHub Pages route like this [lesson from Programming Historian](https://programminghistorian.org/lessons/building-static-sites-with-jekyll-github-pages)?

**Comment by mbonsma** [comment]
@joelostblom check out the topics on [Programming Historian](https://programminghistorian.org/lessons/?topic=python) (thanks @chungkky) - maybe you could combine a few of the modules about text analysis from there?

**Comment by dcwalk** [comment]
Hey! My sense is that Jekyll & Github pages may be too many concepts if the goal is to just get a website up (and without git/version control being covered)

A fellow Faculty of Information PhD, @jackjamieson2, has taught wordpress for beginners before, so looping him in here as he may be able to assist!

I'm out of the country then, so won't be able to

**Comment by ludicpress** [comment]
Hey guys, Chris here from the DHN. For the website option we will basically be dealing with people who have never built a site before. So showing them the ins and outs of WordPress or another appropriate tool + some basic HTML&CSS would be perfect. Our thoughts at the DHN is that if we show them how to use a tool they've heard of they are more likely to enjoy coding in HTML&CSS.

**Comment by chungkky** [comment]
Sorry everyone. I was away all day at a workshop (will be again on Thursday) so am responding late.  I think I'll start another discussion thread on the topic of teaching coding to humanists and social scientists but will reply to the immediate issues here.      

Hi @joelostblom, I don't want to under estimate humanist but NLP with Python is probably too complicated for novices who do not usually use the CLI for their work. Or, at least, other things probably need to be learnt first?

Likewise, I agree with @dcwalk and @chrisjyoung16.  Jekyll is too complicated for an intro to web sites for humanists.  It was difficult for science grad students, who already had GitHub accounts, to set up Jekyll on their computer at the workshop I attended.  For humanists who may not have prior experience with Git or GitHub (even though @mbonsma taught a workshop last year), who don't usually work with the CLI, just installing Jekyll would be a lesson in itself.  (BTW, I disagree with Visconti on the Programming HIstorian lesson; difficulty level is not "low" for building a static website with Jekyll and GitHub Pages!!!!)

Back to topic:  I can teach a lesson on Intro to HTML, Markdown, the concept of mark up languages, and very Intro to CSS .  I'm not a regular user of WordPress so would rather not teach it unless no one else is available.  Alternatively, I might be interested in teaching a session on web site creators in general, not necessarily WordPress.  The basic concepts, difference btw dynamic and static sites, difference btw a full blown CMS with all the bells and whistles (i.e. WordPress) and a minimalist blogger site, hosted vs. self-hosting sites, what the heck is a "server", etc. and then maybe a hands on bit with something (maybe WordPress, maybe an alternative? Ghost? Weebly? I can also consult with the Leslie Barnes, the Digital Scholarship Librarian at UTL for suggestions, esp. if there is anything hosted by U of T, which may be a consideration in terms of FIPPA when related to students' work).

Cheers, -- K.

**Comment by jdpigeon** [comment]
I'd just like to point out that John Ladan put together an awesome presentation for the last intro to HTML/CSS/JS lesson: https://github.com/jladan/webdev-basics

Also, my slides from last year are here: https://docs.google.com/presentation/d/1zNK5CxNGmlZ0hvDL1zVmqaV8ER48vXXrG2M6bu3gNno/edit?usp=sharing

Feel free to use them

**Comment by jackjamieson2** [comment]
Thanks @dcwalk for looping me in,

I'd be happy to teach about WordPress if that's helpful. I've taught WordPress to several generations of journalism students at Ryerson, and I think DHI scholars have similar needs. Probably easier to demonstrate hosted sites at wordpress.com, which limits some options but still covers the basics. 

I also agree with @chungkky that a general web site creators session would be useful.

**Comment by mbonsma** [comment]
This is such an awesome thread! @jackjamieson2 and @chungkky - it would be wonderful if between the two of you we could have a day of WordPress / HTML / website stuff. I'm not sure what makes the most sense in terms of structure and order, but let me know what you think about this plan:

Morning: @chungkky covers:
* > basic concepts, difference btw dynamic and static sites, difference btw a full blown CMS with all the bells and whistles (i.e. WordPress) and a minimalist blogger site, hosted vs. self-hosting sites, what the heck is a "server", etc. 
* hands-on mark-up: HTML, markdown, maybe using [HackMD](https://hackmd.io/)?

Afternoon: @jackjamieson2 teaches us how to make a WordPress website!

**Comment by mbonsma** [comment]
Also @joelostblom and Raul are our Python people so far.

**Comment by jackjamieson2** [comment]
@mbonsma That sounds promising to me.  Definitely makes sense to do the more general overview before WordPress.  On the 12th, I'm teaching in the afternoon, so I can only be available on the 11th or before noon on the 12th

**Comment by chungkky** [comment]
Thanks for the pointers @jdpigeon.  I'll look into them for sure.  @mbonsma,  I'm good with doing the morning of the 11 Dec with a short intro to mark-up languages (presentational, semantic, procedural), websites in general with some jargon busting (servers, clients, ftp, CMS, static/dynamic sites, etc), then intro to HTML/CSS/Markdown/editors which can lead to @jackjamieson2 doing a more specific afternoon workshop WordPress.  I'll get in touch with @jackjamieson2 to coordinate so our two workshops compliment each other. Ok?

**Comment by mbonsma** [comment]
@jackjamieson2 and @chungkky that sounds great: @chungkky on the morning of the 11th, and @jackjamieson2 in the afternoon on the 11th. Feel free to cc me on emails if you want and we can talk about software / hardware needs in the next few weeks.

**Comment by joelostblom** [comment]
Hello @dcwalk @jackjamieson2 @chungkky @chrisjyoung16,

I would like to ask for your opinion on what to include during the afternoon Python session of the workshop (there will be an introduction to Python in the morning).

I am not familiar with which topics would be the most useful for DHN students, but using [this list](https://programminghistorian.org/lessons/?topic=python) from the programming historian as a basis, I have the following suggestions:

1. How to use Python with HTML and webpages - downloading pages, and extracting words from html.
2. How to use Python to work with textual data - reading/writing files, counting and plotting ngrams, wordcounts and wordclouds.

I am more familiar with topic 2, and would be inclined to teach that. Do you have an opinion regarding which of these would be more useful? Do you have a suggestion of a topic or subtopic you think I should include instead/in addition to what I wrote above?

**Comment by chungkky** [comment]
Hi @joelostblom @jackjamieson2 @chrisjyoung16, @dcwalk 

It's a hard choice.  I'm sure people would be interested in both topics.  Scraping HTML pages is probably more "sexy" but at the same time, I think you should teach what you are most comfortable with. You'll do a better teaching job, and text manipulation and analysis are useful to humanists.  At the end of that workshop, you can always poll people whether they have further interest in scraping websites and we can offer another workshop on that later in the winter/spring. 

Additional comment: In the spirit of "Know Your Audience" -- you might consider talking about or acknowledging the pros and cons of using Python to do text analysis and comparing it with an "out of the box" program/application (when did "programs" turn into "applications"?) like "Voyant Tools," which you can check out here: 

* [https://en.wikipedia.org/wiki/Voyant_Tools](https://en.wikipedia.org/wiki/Voyant_Tools) 
* [http://voyant-tools.org/](http://voyant-tools.org/)
* [http://voyant-tools.org/docs/#!/guide/start](http://voyant-tools.org/docs/#!/guide/start)  

Voyant has been around for a while and it is Canadian made! It has limitations but it is easier for non-techies to use (no coding involved!). Teaching people how do it with Python lets them see under the hood and gives them more control.

Cheers, -- K.

**Comment by joelostblom** [comment]
Great, thanks @chungkky ! I will make sure to mention voyant tools, never heard of it so good that you posted about it!

Everyone else, let me know if you have different suggestions. I am currently thinking I might be able to fit some brief HTML scraping in the beginning to obtain the text to do the rest of the analyses on.
