### ISSUE TITLE
Suggestions for session topics you'd like to see in 2018?

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#324]
some suggestions so far:
- @SaraMati has some good stats recommendations here: https://github.com/UofTCoders/council/issues/208 basically: 
    1. David Groppe, to have a 'coding statistical techniques'
    2. John Griffith, to have a ' tools for reproducible research'
- a 3D Printing lesson (how to design a print, or use templates and general concepts of 3D printing)
- @lcoome suggested a UX Design lesson

If you have any suggestions of topics you'd like to see (or teach!), please post them here. Also, if you know of lesson material we could use for that topic, that'd be very helpful, but not required.

Thanks!

**Comment by jdpigeon** [comment]
Any interest in React? I'd be happy to teach it.

As far as learning, I'd love to learn about MNE python and dynamic charts with d3.js or charts.js

**Comment by ralle123** [comment]
I could do an intro to d3.js  =)

**Comment by lwjohnst86** [comment]
Some ideas:

- Defensive programming (R and Python)
- Statistical methods for R (intro and advanced)
- R Markdown (intro and advanced)
