### ISSUE TITLE
CAMH Neuroimaging Lab Seeking Research Methods Specialist

### ISSUE THREAD

**Issue by edickie** [UofTCoders/studyGroup#325]
The Kimel Family Translational Imaging-Genetics Laboratory is a large multidisciplinary research laboratory dedicated to discovering the causes of severe mental illness and advancing treatments for severe mental illness. The focus of the laboratory is on combining brain imaging and genetics, brain imaging and brain stimulation, and brain imaging and clinical trials.
 
The Research Methods Specialist’s primary responsibility will be to collaborate and support laboratory members and subject matter experts in design, development and implementation of analyses and new methods, as well as provide guidance, technical advice and training. The successful candidate will also be involved in the maintenance of different analysis pipelines and will help users migrate existing software to high performance computing infrastructures (such as the SciNet facilities). Additionally, the Research Methods Specialist will be involved in the system administration of a computing cluster that is used in the daily research endeavours of scientists, fellows, and trainees. In this role you will manage both user access and hardware of the cluster. You will support a healthy workplace that embraces diversity encourages teamwork and complies with all applicable standards and requirements. This position will be located at 250 College Street.

For more info and to apply visit:
http://www.recruitingsite.com/csbsites/camh/JobDescription.asp?SuperCategoryCode=15233&JobNumber=816025&lang=en

**Comment by jdpigeon** [comment]
You should post this in the NeuroTechX slack! #opportunities channel

**Comment by edickie** [comment]
Great idea! @jdpigeon can you send me an invite to neurotechx slack?

**Comment by lwjohnst86** [comment]
I assume the job has been filled since the link doesn't appear to work anymore. Closing
