### ISSUE TITLE
Open Satellite Ground Station on U of T campus 

### ISSUE THREAD

**Issue by dcwalk** [UofTCoders/studyGroup#327]
Hey all, (long time)

I watched a couple really great talks at 34c3 from the [Libre Space Foundation](https://libre.space/) and [SatNOGS](https://satnogs.org/faq/) about DIY ground stations. I think it would be awesome to get one up and running!

Talk is here:
- https://media.ccc.de/v/34c3-9189-satnogs_crowd-sourced_satellite_operations
- https://youtu.be/KiMXW6URg0U

The current network, docs are here: 
- https://network.satnogs.org/
- https://wiki.satnogs.org/Main_Page

Maybe we could have a chat at an upcoming co-working sesh? The biggest barrier I see is roof access, but not impossible!

**Comment by QuLogic** [comment]
You need to make friends with some CITA people...

**Comment by mbonsma** [comment]
This is super cool!

**Comment by dcwalk** [comment]
Hey! In some weird procrastination moment I'm grooming my old open issues 🤷‍♀️ 
I'm gonna self-close this so I don't clutter up your issues and I didn't follow up on the thought and maybe no one else did either?

If that is the wrong move someone feel free to re-open!

**Comment by mbonsma** [comment]
@dcwalk as far as I know, there was some interest among the Coders but no one followed up specifically. We can leave it closed and if a moment of freedom or inspiration strikes, maybe it will happen someday :)
