### ISSUE TITLE
Software Carpentry Jan 18-19 -- call for helpers / attendees

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#329]
U of T Coders is hosting a hands-on two-day Software Carpentry workshop covering core small research team skills. Through short tutorials and practical exercises, attendees will learn:

- Automating tasks with the Unix Shell
- Version control with Git
- Programming with R

**You don't need to have any previous knowledge of the tools that will be 
presented at the workshop.**

When: January 18-19, 9 am - 4 pm
Where: MADLab, Gerstein Science Information Centre, Room B112
Cost: $25

[Website](https://uoftcoders.github.io/2018-01-18-utoronto/)
[Facebook event](https://www.facebook.com/events/924326097716437/)

We are also looking for helpers to attend all or part of the workshop (for free). The schedule is:

Jan 18 morning: Bash
Jan 18 afternoon: R
Jan 19 morning: Git
Jan 19 afternoon: R

Send an email to uoftcoders@gmail.com or comment here if you're interested in helping out and let us know when you're available.

**Comment by HebaF** [comment]
Hi Madeleine,


This will be the first event that I come out to, but I can commit to helping with the Thursday January 18 R session. Would the afternoon session be from 1pm-4pm?


Best,

Heba Farookhi

________________________________

**Comment by ralle123** [comment]
Hello Madeleine,

Let me know if you need help with the R part. Perhaps I could come in and
help if nobody else shows up =)

-- 
Thanks,

Raul

**Comment by mbonsma** [comment]
Hi @HebaF, that's great! Yes, the afternoon session is from 1-4. All you need to do is show up at that time!

**Comment by mbonsma** [comment]
And @ralle123 thanks! So far there aren't too many helpers so I'll put you down on the list.
