### ISSUE TITLE
Toronto Datathon: Cash Prizes + Career Opportunities

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#331]
Below is some information about a cool-sounding upcoming [Toronto Datathon](https://www.citadel.com/careers/the-data-open/apply/).

------------------------

Datathons are a new type of live-action competition for STEM students. They are analogous to "Hackathons" for software engineers, but instead of building apps, contestants use real-world data to develop and substantiate solutions to a socially impactful problem. If you are curious to see what a Datathon looks like, we encourage you to view this [brief clip](https://www.youtube.com/watch?v=F0nQJcB8rhI) from our past event in Dublin!

The Toronto Datathon is hosted by Citadel LLC & Citadel Securities in partnership with Correlation One. The event will take place on **Saturday, January 27th** from **8:00am-6:00pm in the Fleck Atrium at the Rotman School of Management**. There will also be an exclusive Citadel Networking Reception on Friday evening at the Toronto Stock Exchange for all invited Datathon participants.

 *   $25,000 in cash prizes! 
 *   The chance to showcase your skills tackling a meaningful, real-world problem!
 *   The opportunity to participate at The Data Open and win $100,000 in cash prizes!
 *   Possible interviews with Citadel & Citadel Securities!

Sign up [HERE](https://www.citadel.com/careers/the-data-open/apply/) to complete the Questionnaire, Assessment and Registration!

If you have any further questions, please direct them to victor@correlation-one.com. Thank you, and we look forward to receiving your application and hope to have you in attendance with us on Saturday, January 27!
 
**Note**: We're currently working on fixing an issue that prevents some students without a ".edu" email address format from signing up. You can still sign up with an official school email address by simply typing ".edu" at the end of it. For example, you can enter "jsmith@toronto.ca.edu" and then still progress through the application.

**Comment by jdpigeon** [comment]
Just for students?

**Comment by mbonsma** [comment]
There's still space for this if anyone is on the fence about signing up!
