### ISSUE TITLE
Winter/Spring 2018 Sessions + Call for instructors

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#334]
Hi Everyone,

Thanks so much for filling out our 2018 topic survey. We've parsed it down to 10 topics for this semester, but will look back at the results for any we may have missed for the summer session so fret not if your favourite topic isn't listed.

Feb 1 - Machine Learning for Computational Biology using R - Davide
Feb 8 - Image Processing in Python - Nil
Feb 15 - ggplot2 in R - Ahmed
Feb 22 - Open source tools for graphics/diagrams (e.g. Inkscape) - John L
March 1 - Intermediate Topics in R 
March 8 - What is Blockchain? - Elena from [CrytoChicks](https://www.meetup.com/Blockchain-and-cryptocurrencies-for-ladies/)
March 15 - Intro to 3D Printing + Certification - Mike Spears
March 22 - Neural Networks in Python (Keras, Tensorflow etc.) - Sara & Nil
March 29 - Academic Workflows - John G
April 5 - Interactive Plotting (Bokeh, Shiny, D3 etc) - Raul

Those marked with an (*) need instructors, so if you're interested in teaching this lesson, please email us at uoftcoders@gmail.com with which lesson you'd like to teach, and whether the date works for you.

**Comment by ralle123** [comment]
Hello:

Is the interactive plotting topic still available for April 5th?
If it is can I do it?
let me know.
-- 
Thanks,

Raul Samayoa
https://ca.linkedin.com/in/rsamayoa

**Comment by linamnt** [comment]
Hi @ralle123 , Yes it's still in need of an instructor. Thank you for volunteering! We will send an email closer to the date to remind you, for now you can take a look at our [Contributing Guidelines](https://uoftcoders.github.io/studyGroup/CONTRIBUTING/#running-a-lesson) for planning a lesson.
