### ISSUE TITLE
Looking for tutor in programming and scientific computing (R)

### ISSUE THREAD

**Issue by madlenlang** [UofTCoders/studyGroup#342]
I am and MSc student at UofT currently taking an R based statistics course and really struggling with the weekly/biweekly assignments.  I'd also like to use R in my own research. However, the course moves at a pretty fast pace and I am having trouble applying material we learned in lecture to the assignments let alone my own data. I would be interested in a once a week tutoring session for the remainder of the semester to help with the coding aspect of the course. This is of course something I'd be willing to compensate for financially. 

If you are interested or know of someone who might be, feel free to contact me at madlen.lang@mail.utoronto.ca

Best,

Maddy

**Comment by mbonsma** [comment]
Hi @madlenlang! I'm not sure if you've heard back yet over email, but I just wanted to mention that tomorrow's UofT Coders session will be R-focused ([Intro to ggplot2](https://github.com/UofTCoders/Events/issues/136)) and if you're available, I'd encourage you to come to that! There will be people there who can help one-on-one as well.

**Comment by joelostblom** [comment]
@madlenlang Please reopen if you are still looking for help with this. Note that our next three sessions will be focused on R https://uoftcoders.github.io/studyGroup/#events
