### ISSUE TITLE
Looking for a developer (preferably female) for help with an app to empower women in STEM 

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#347]
Are you interested in creating an exciting app to empower women? [Sarah Firestone](https://twitter.com/firestone_sarah), a student in the Faculty of Law, is looking for a coder/developer to be part of a project to create an app for women's mentorship. If you're interested in chatting with her about it, she'll be at the [next UofT Coders session (Feb 22)](https://github.com/UofTCoders/Events/issues/138), or feel free to contact her directly.

**Comment by joelostblom** [comment]
@mbonsma Please reopen if application are still accepted for thie
