### ISSUE TITLE
DataSci Team

### ISSUE THREAD

**Issue by ghost** [UofTCoders/studyGroup#348]
Looking for people to tackle some Kaggle competitions. Reply here or email me if interested (andrei.mouraviev@mail.utoronto.ca).

**Comment by ghost** [comment]
Slack [channel](https://join.slack.com/t/uoft-kaggle-team/shared_invite/enQtMzE1NzQ1OTkwMDE2LWU2MjZhMDJjMmJiM2EzYjQ0NzA4Zjk2ZTM5YTgyOGJiNGVmNGE0Y2UzMDBhNmRhNmM4NGVlNjg0ZmU5ZjI5Njg)

**Comment by bibin-sebastian** [comment]
Hi @andreimouraviev . I was looking for something similar . Can we connect ?

**Comment by QuLogic** [comment]
As the original user, and the slack channel invite, no longer exist, I'm going to close this.
