### ISSUE TITLE
2018 Mozilla Global Sprint, May 10-11

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#354]
The [Mozilla Global Sprint](https://foundation.mozilla.org/opportunity/global-sprint/) is a fun, worldwide, 2-day hackathon **May 10-11** that includes a huge diversity of people, locations, and projects. You can participate online, or by joining a physical site near your location. There’s a Global Sprint Host Site right here in Toronto that will be open from 9am to 5pm on May 10 & 11. Use this link to register: https://ti.to/Mozilla/global-sprint-toronto18.

You can join in and participate, no matter your skill set or level. We’re looking for coders, designers, writers, educators, students, and more— anyone who’s passionate about the open web. We’ve got a terrific group of projects that need help-- check out our list of featured projects. All that’s missing is you!
Here’s more on how to participate in the Sprint https://foundation.mozilla.org/opportunity/global-sprint/participate/

**Ways to participate**:
 * [Submit a project](https://foundation.mozilla.org/opportunity/global-sprint/lead-a-project/) to lead at the sprint. This is way less scary than it sounds, and I strongly encourage anyone with a twinkling of an idea to try it out at this event! 
 * [Register to participate](https://foundation.mozilla.org/opportunity/global-sprint/participate/), and work on other submitted projects during the two days of the sprint.

**Comment by lwjohnst86** [comment]
Finished! Great job for those who participated! :smile:
