### ISSUE TITLE
event schedule for summer

### ISSUE THREAD

**Issue by ralle123** [UofTCoders/studyGroup#375]
hello, wanted to see if there is a tentative schedule for summer events. I am at pycon right now and there is plenty of awesome things to see here lol

**Comment by ralle123** [comment]
can I do a talk about virtualization vs docker for data science or working with data?

**Comment by linamnt** [comment]
Hi Raul, we'll be sending out the schedule as soon as we confirm our instructors etc. 
Would it be possible to keep this on deck for the fall? If we keep up with our themed lesson series, we can think about a Series this could fit into, something like a Data Wrangling/Analysis, Using Other Peoples Code etc. Thanks!

**Comment by ralle123** [comment]
sure let know when and I can do it anytime
