### ISSUE TITLE
Summer 2018 Schedule + Opportunities to Teach

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#378]
Date | Session | Instructor
-- | -- | --
**R Series**
May 17 | Intro R | @franceswong
May 24 | [Intro Statistics in R](https://github.com/UofTCoders/Events/issues/156) | @lcoome 
May 31 | [Intermediate Statistics in R + Missing Data](https://github.com/UofTCoders/Events/issues/157) | @zoelynnfrancis
**Reproducible Documents**
June 7 | [Lightning Demos - Your favourite text editor](https://github.com/UofTCoders/Events/issues/160) | @joelostblom @aays @linamnt @jdpigeon
June 14 | [Intro Bash](https://github.com/UofTCoders/Events/issues/159) |  @joelostblom 
June 21 | [Intro Latex](https://github.com/UofTCoders/Events/issues/158) |  @SaraMati  
June 28 | [RMarkdown, Markdown and Pandoc](https://github.com/UofTCoders/Events/issues/161) | @linamnt + @SaraMati 
**Gadgets and Hardware**
July 5 | [Gadgets and Hardware](https://github.com/UofTCoders/Events/issues/163) | @bksutherland
July 12 | Coworking Gadgets | NA
**Python Series**
July 19 | Intro Python |  @joelostblom 
July 26 | Measures of association and statistical testing of hypotheses in Python using SciPy  |  Tomas
Aug 2 | Webscraping |  Riyad
Aug 9 | Coworking Python |  NA
**Contributing to Open Source Projects**
Aug 16 | Intro Git |  
Aug 23 | Contributing to an Open Source Project 101 |  @QuLogic 
Aug 30 | Virtualization vs. Docker Images, Sphinx for Documentation | @ralle123
Sep 6 | Coworking Session - Bugs/Pull Reqs |  NA

## Call for Instructors

We wouldn't be able to hold these weekly sessions without volunteers from the UofT Coders community, and we're always welcoming of any new volunteers who would like to teach or help in other ways. If you'd like to volunteer to instruct one of these sessions, please reply here or to uoftcoders@gmail.com with the following:

- Which session you'd like to teach
- A quick outline of what you would like to cover
- Confirm you've read our [Contributing Guidelines for Leading a Lesson](https://uoftcoders.github.io/studyGroup/CONTRIBUTING/#leading-a-lesson)

We will get in contact with you thereafter to coordinate.

Note: You DO NOT need to be an expert in the lesson topic to teach! While some familiarity is required, if you'd like to use this as an opportunity to further your understanding of the topic, we highly encourage that as well!

**Comment by FrancesWong** [comment]
Hey!


I can help out with the Intro to Latex but I'm going to be away in Edmonton from June 14 to 24th. Are there any flexibility in the dates?


Best,

-Frances


Frances Wong, Hon. B.Sc.
Ph.D. Candidate | Brian Cox Laboratory
Faculty of Medicine | University of Toronto | Physiology
1 King’s College Circle
MSB 3360
Toronto ON | M5S 1A8
frances.wong@mail.utoronto.ca | (416)-978-3240


________________________________
