### ISSUE TITLE
A bulletin board for cs events and opportunities for UofT students!

### ISSUE THREAD

**Issue by wenqinYe** [UofTCoders/studyGroup#382]
Hello I'm Wenqin, and I am a second year CS student at UofT.

I made a digital bulletin board for cs events and opportunities at UofT. Right now it is just a firebase app (no official domain), but do check it out: [https://showandtell-8a517.firebaseapp.com/c/computer_science_opportunities](https://showandtell-8a517.firebaseapp.com/c/computer_science_opportunities)

I have already added some of the opportunities posted in this group but am wondering if you all know of any other events or opportunities to share. If you do, feel free to add it to the site, or leave a comment and I can add it for you :)

The goal is to have a single, community updated, repository for events/opportunities on campus. 

If you have further questions or just want to chat you can reach my by email at wenqin908@gmail.com or on twitter @wenqinYe

Cheers,
Wenqin

**Comment by mbonsma** [comment]
Hi @wenqinYe, this is really cool and a great idea! Here are a couple of other CS-related groups and lists I know about. I'm not sure what all of them are up to these days but I hope this helps! 

### UofT groups:
* Skule Digest: http://digest.skule.ca/
* CSSU: https://cssu.ca/
* U of T WICS (Women In Computer Science): https://www.facebook.com/UofTWiCS/
* Galbraith Society (Skule) http://gsociety.skule.ca/
* Hacker Academy: https://www.hackeracademy.org/
* University of Toronto Developers: https://www.facebook.com/groups/UofTDev/about/
* The Entrepreneurship Hatchery: https://hatchery.engineering.utoronto.ca/
* Game Design and Development Club: http://www.utgddc.com/
* Web Development Club (WDC): https://cssu.ca/clubs/2017/10/23/WDC.html
* Rotman Business Technology Association: https://inside.rotman.utoronto.ca/bta/
* Internet Research Network: http://internetresearchnetwork.org/
* Machine Learning Club, http://machinelearning.sitey.me/ 

### Toronto groups:
* Toronto Machine Learning Summit: https://torontomachinelearning.com/
* CivicTechTO: http://civictech.ca/
* BrainHack: https://camh-scwg.github.io/to-brainhack-2018/

**Comment by mbonsma** [comment]
Also, there are a few other things listed if you scroll down to the very bottom of our website: https://uoftcoders.github.io/

**Comment by wenqinYe** [comment]
Thank you very much @mbonsma for creating such a comprehensive list 😃

Now I'll just have to work hard to collect the events together and share them with you and others

**Comment by linamnt** [comment]
Closing for now, as new events haven't been added since last year. But definitely feel free to reopen if there are updates :+1:
