### ISSUE TITLE
Notes from Hacky Hour #1

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#4]
_Here's a [Doodle poll](http://doodle.com/xubabx65hd954zs3) for availability for next week’s meeting._

Over 20 people came out to our first meeting, and many awesome ideas were discussed. Here’s a summary of what was talked about.

**Study group purpose and goals (from the [Mozilla Study Group Handbook](http://mozillascience.github.io/studyGroupHandbook/))**
- Skill sharing – coding help and advice for and from peers
- Idea discovery – finding, sharing, and re-using open source code
- Community support – saying goodbye to imposter syndrome, encouraging peers and dissolving isolation

**Code of conduct** – we’ll be using a slightly modified version of the [Mozilla Science Lab Code of Conduct](https://www.mozillascience.org/code-of-conduct/), which I’ll post on our blog once it’s up.

**Staying in touch**
- We’ll be using the Github issue tracker for announcements and idea sharing.
- We have a [Gitter chat room](https://gitter.im/mbonsma/UofTstudyGroup?utm_source=share-link&utm_medium=link&utm_campaign=share-link).
- We want a blog - @dchandan suggested Github pages (which is what the main website is in already). Anyone interested in taking a crack at this, you’re on (see ‘To do’ at the bottom).  

**Admin stuff**
- If you want to make events and edit pages and stuff, let me know and I'll add you as a collaborator on this repository.
- @atavasoli will be heading this up – this includes becoming a ‘recognized group’ on campus so that we can book rooms for free and stuff like that, and possibly applying for the [Student Initiative Fund]() so that we can have some money. Snacks on snacks. 

**Ideas and Decisions**
-   People are interested in a few different languages and there’s lots of overlap, so we’ll stay as one group but people can pick and choose which sessions to attend based on topic. 
-   Our second meeting will be an introduction to Git presented by Luke, which will be next week sometime. Fill out the [Doodle poll](http://doodle.com/xubabx65hd954zs3) with your availability – we’ll pick a time for next week that works for Luke and lots of people (probably not Monday), but in following weeks this might change if there’s a better day. It will be in the Physics building, room TBA. Dominque will bring cookies!
-   Other room booking options: SciNet, Robarts, Bahen, and probably others once we get recognized group status. 
-   Our third meeting will most likely be a [coworking session](http://mozillascience.github.io/studyGroupHandbook/events.html) so that we can get to know each other some more and learn informally what the group is interested in.  We also like the idea of code lightning demos where more than one person very quickly demos a topic at a session. 
-   We should have some discussion topic threads for some broad subject areas so people can post ideas for events and presentations and also share open source tools.
-   We want a permanent list of ‘resident experts’ for different tools and languages – this could live on the blog – so that you can always find someone who might be able to help. 

**To do (everyone)**
-   Fill out the [Doodle poll](http://doodle.com/xubabx65hd954zs3).
-   `watch` this repository to get updates.
-   Post ideas, suggestions, things I missed, and discussion topics in the issue tracker.

**To do (some people)**
-   Become a recognized group, maybe apply for the Student Initiative Fund (@atavasoli).
-   Make a blog (@dchandan?).
-   Book a room for next week (@mbonsma).

**Comment by QuLogic** [comment]
> Make a blog

Make a file in `studyGroup/_posts/` (like the existing `2015-06-11-HackyHour.markdown`) and it gets listed as a post under Events. So the simplest is to just change the title from Events to Blog and continue on like that.

**Comment by abbycabs** [comment]
Also, I believe cookies were on the agenda for next week :cookie:

**Comment by mbonsma** [comment]
TIL: how to make a :cookie: in Markdown.

**Comment by abbycabs** [comment]
http://www.emoji-cheat-sheet.com/

**Comment by mbonsma** [comment]
@QuLogic I added you as a collaborator, so if you feel like making some bloggy pages, go ahead! No pressure though.

**Comment by lwjohnst86** [comment]
I've moved this into a [wiki page](https://github.com/UofTCoders/studyGroup/wiki/Notes-from-Hacky-Hour-1), so it can be closed.
