### ISSUE TITLE
Data Carpentry - September 10-11 - Call for helpers / attendees

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#401]
U of T Coders is hosting a hands-on two-day [**Data Carpentry**](http://www.datacarpentry.org/) workshop covering core small research team skills. Through short tutorials and practical exercises, attendees will learn:

 * Data organization and cleaning
 * Data analysis and visualization with Python
 * Skills for reproducible scientific analysis

**You don't need to have any previous knowledge of the tools that will be 
presented at the workshop.**

When: September 10-11, 9 am - 4:30 pm
Where: MADLab, Gerstein Science Information Centre, Room B112
Cost: $25

[Website](https://uoftcoders.github.io/2018-09-10-utoronto/)

We are also looking for helpers to attend all or part of the workshop (for free). The schedule is:

**September 10 morning:** Intro to programming, intro to Python and Jupyter notebooks, data organization and cleaning
**September 10 afternoon:** Data analysis and visualization in Python, part 1
**September 11 morning:** Data analysis and visualization in Python, part 2
**September 11 afternoon:** Advanced data wrangling and visualization in Python

Send an email to uoftcoders@gmail.com or comment here if you're interested in helping out and let us know when you're available.

**Comment by sergiosonline** [comment]
Looks great! I'm interested in helping--what would my responsibilities be?

**Comment by mbonsma** [comment]
@sergiosonline - awesome! Helpers float around the room and help one-on-one with answering questions and debugging when things don't work. You don't have to know the material super well, it's usually enough that you pay attention during the session so that you know what people are trying to do.

All the lesson material is [here](https://github.com/UofTCoders/2018-09-10-utoronto/tree/gh-pages/code), although we are hoping to change the dataset before the workshop.

You can come for whichever section you like and stay as long as you want to / are able to.

**Comment by bibin-sebastian** [comment]
I am also interested in helping. please let me know if you have space available
