### ISSUE TITLE
Outreach and planning for September - December

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#42]
The new academic year is almost upon us! This issue is a place to discuss, plan, and share strategies and materials for getting the word out about the Study Group. 

In June, many of you got an email from your department with a link to the repo and issue tracker and a link to [this survey](https://docs.google.com/forms/d/1QIRsnaJjpf5sTV_nMC9KEA44Mz21wuASDxttdgTBj44/viewform?usp=send_form). 

I also posted an announcement similar to the one below to the GSU mailing list which goes to all grad students:

>  **Mozilla Study Group: Thursdays at 6 pm**
> The Mozilla Science Lab has started a series of meetup groups for scientists and researchers to get together, share coding skills, and help each other out with the programming many have to do as part of research. Topics from across the spectrum of scientific computing are covered. The study group meets on Thursdays at 6:00 pm in MP408. To receive updates on future sessions, follow the UofTCoders Events repository on Github (https://github.com/UofTCoders/Events) or send an email to Madeleine at m.bonsma@mail.utoronto.ca

Questions for you:
1. What changes (if any) should be made to the [survey](https://docs.google.com/forms/d/1QIRsnaJjpf5sTV_nMC9KEA44Mz21wuASDxttdgTBj44/viewform?usp=send_form)?
2. What changes should be made to the email or GSU announcement?
3. What other avenues of communication should we explore?

PS. New meeting time for late September - December: fill out the [Doodle poll!](http://doodle.com/avkeivgie8zh32ti)

**Comment by mbonsma** [comment]
Check out the Mozilla Study Group Handbook's outreach templates: [one to get the word out](https://github.com/mozillascience/studyGroupHandbook/blob/gh-pages/templates/startOfTermLetter1.md), and [one to call for instructors](https://github.com/mozillascience/studyGroupHandbook/blob/gh-pages/templates/startOfTermLetter2.md).

**Comment by katieannemills** [comment]
Yes - and feel free to send me comments on those templates too! Would love to learn from how U of T is executing on this, and have your experience help shape the Handbook.

**Comment by abbycabs** [comment]
Sorry I missed the planning session, but have you looked at UofT's clubs day / street fest?

http://www.orientation.utsu.ca/#!clubs-registration/c6x0

This may be more frosh oriented than your audience, but I've always gotten a good amount of contacts there.

**Comment by mbonsma** [comment]
That's a great idea!

**Comment by lwjohnst86** [comment]
At this point we won't be able to do the Club's day because we are not a recognized UofT group. Only those who are recognized can register to be part of the club's day. Given the timeline, it might not be feasible this year to do it, but later years we should definitely do this.

**Comment by mbonsma** [comment]
Agreed. If anyone is interested in helping with recognition and funding applications, check out issue #6.

**Comment by abbycabs** [comment]
They usually have another clubs event in January :) Getting group status is probably a good route.

**Comment by mbonsma** [comment]
Reminder! If you emailed your departmental mailing list with an announcement about the group, comment here so that I don't repeat your department when I send out more emails on Monday.

**Comment by lwjohnst86** [comment]
Thanks for the reminder. I've sent it to the Department of Nutritional Sciences.

**Comment by cczhu** [comment]
I've sent one to Astronomy & Astrophysics.

**Comment by linamnt** [comment]
Physiology has received the email as well.

On Mon, Sep 14, 2015 at 2:14 PM, Charles Zhu notifications@github.com
wrote:

> I've sent one to Astronomy & Astrophysics.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/42#issuecomment-140164132
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by mbonsma** [comment]
Okay great. This morning I emailed these departments:

Physics
Biochemistry
CSB
Chemical Engineering
Chemistry
Computer Science
Earth Science
EEB
Economics
Geography
Immunology
Lab Medicine and Pathobiology
Linguistics
Materials Science & Engineering
Math
Mechanical and Industrial Engineering
Medical Biophysics
Medicine
Molecular Genetics
Pharmacology and Toxicology
Ophthamology & Vision Sciences
Physiology
Political Science
Psychiatry
Sociology
Statistics
Anthropology
OISE
Applied Psychology and Human Development (under OISE)
Astronomy and Astrophysics
Chemical Engineering
Classics
East Asian Studies
ECE
English
Germanic Languages and Literatures
History
Art
Italian Studies
Near and Middle Eastern Civilizations
Occupational Therapy
Philosophy
Rehabilitation Science
Religion
Slavic Languages & Lit
Spanish & Portuguese
Speech-Language Pathology
