### ISSUE TITLE
Interested in Building a Graphic of a Co-Citation Network?

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#421]
Dr. Daniel Silver, an associate professor in Socialogy at UTSC is looking for someone to help with a graphic for a publication. 

He has a co-citation network of texts, broken up into some
clusters and would like to figure out a way to make a nice clean visual of
the main structure of the overall network, and then also of the clusters
separately.  This is for an article that will appear in the Annual
Review of Sociology, about the influence of an author (Georg Simmel) on
the discipline. 

Graphic design + text analysis skills ideal.

If you're interested in helping with this graphic (you willl receive a monetary compensation) please contact Daniel Silver (dsilver@utsc.utoronto.ca).

**Comment by jessexknight** [comment]
Is this still relevant?  -- it seems old. Perhaps we can close as stale?

(though I would have been happy to help!)

**Comment by linamnt** [comment]
Thanks, closed as they are no longer looking for someone.
