### ISSUE TITLE
How to transform lon/lat values generated by ax.scatter

### ISSUE THREAD

**Issue by zxdawn** [UofTCoders/studyGroup#423]
@QuLogic Thank you for your [tutorial](https://github.com/UofTCoders/studyGroup/blob/gh-pages/lessons/python/cartography/Cartography%20and%20Mapping%20in%20Python.ipynb) about Cartography.

I edited part of your script and you can check that [here](https://github.com/zxdawn/studyGroup/blob/Cartography/lessons/python/cartography/test_projection.py).

The script is written for get the **location of clicking point** and set it as the **title** of another subplot.
But, `event.ydata` and `event.xdata` are very large values.

**Q:**
What's the meaning of these large values and how to transform them to lon (-180 ~ 180) and lat(-90 ~ 90)?

Thank you in advance!

**Comment by QuLogic** [comment]
The location is in map units; for Lambert Conformal that is probably projected metres. If you want longitude/latitude, you'd need to use `transform_point` from Lambert Conformal to Plate Carree.

**Comment by zxdawn** [comment]
Thank you for your help! It works now.
