### ISSUE TITLE
Winter Schedule 2019 + Call for Instructors

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#428]
Hope everyone has been having a great holiday season! We're gearing up for the new year and semester. Take a peek to see which ones you'd like to attend, and if you see a lesson currently without an instructor that you'd like to teach, get in touch about instructing with UofT Coders (more info below).

Also feel free to leave comments about lessons you'd like to see in the future, or ones you'd like to teach yourself. We're always on the hunt for more breadth in the lessons we cover.

**View the events issues with installation and lecture details here:** 
https://github.com/UofTCoders/Events/issues

Date | Session (previous material linked, if applicable) | Instructor
-- | -- | --
Jan 10 | [Intro to Python](https://uoftcoders.github.io/studyGroup/lessons/python/intro/lesson/) | Ahmed
Jan 15 | Coffee and Code | Co-working at Grad House Second Cup
Jan 17 | Intro to R/Tidyverse | Aaron
Jan 24 | [Intro to Bash/Shell Scripting](https://uoftcoders.github.io/studyGroup/lessons/misc/bash-intro/lesson/) | Lina
Jan 29 | Coffee and Code | Co-working at Grad House Second Cup
Jan 31 | Inkscape - An Open-Source Alternative to Adobe Illustrator | Frances
Feb 7 | R: Intro to TidyR and Reshape2 | Raul
Feb 12 | Coffee and Code | Co-working at Grad House Second Cup 
Feb 14 | [Image Processing in Python](https://uoftcoders.github.io/studyGroup/lessons/python/image-processing/lesson/) | Sam
Feb 21 | R: Interactive Plotting with Shiny Apps | Erica
Feb 26 | Coffee and Code | Co-working at Grad House Second Cup
Feb 28 | ~Deep Learning with Tensorflow and Keras~ To be rescheduled. Co-working Session | N/A
Mar 7 | [Git: Continuous Integration and Testing](https://uoftcoders.github.io/studyGroup/lessons/git/ci-github/lesson/) | **
Mar 12 | Coffee and Code | Co-working at Grad House Second Cup
Mar 14 |  Information in the Air - Software Defined Radio | Brian (Tentative Date) 
Mar 21 | Regression Models in R | Amin
Mar 26 | Coffee and Code | Co-working at Grad House Second Cup
Mar 28 | HTML/Web Design | Vince
Apr 4 | Intro to ggplot2 in R | Aaron
April 9 | Coffee and Code | Co-working at Grad House Second Cup
April 11 | Coworking Session | NA
April 18 | Deep Learning with PyTorch | Lina
April 25 | End of Term Social | Location TBD

## Call for Instructors **

We wouldn't be able to hold these weekly sessions without volunteers from the UofT Coders community, and we're always welcoming of any new volunteers who would like to teach or help in other ways. If you'd like to volunteer to instruct one of these sessions (lessons needing instructors indicated with `**`), please reply here or to uoftcoders@gmail.com with the following:

- Which session you'd like to teach
- A quick outline of what you would like to cover. Linked to some of the lessons are previous material that has been developed. You can either reuse the lesson material or adapt it for your purposes.
- Confirm you've read our [Contributing Guidelines for Leading a Lesson](https://uoftcoders.github.io/studyGroup/CONTRIBUTING/#leading-a-lesson)

We will get in contact with you thereafter to coordinate.

Note: You DO NOT need to be an expert in the lesson topic to teach. While some familiarity is required, if you'd like to use this as an opportunity to further your understanding of the topic, we highly encourage that as well :)

**Comment by ralle123** [comment]
Can I take intro to tidyR and Reshape2 on feb 7?
Let me know if you need somebody for the January 10 intro to python and I
can do that too
Thanks
 Raul
