### ISSUE TITLE
PhD student looking for Python Tutor

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#445]
Posted on behalf of a member looking for tutor services:

---

Hello,

I am a PhD student at U of T St. George, looking for a Python tutor with a background in engineering, physical science, and/or computer science.

The specific project will involve solving systems of ordinary differential equations numerically, with parameterization that will change conditionally. Please contact me if you are interested: jacob.kvasnicka@mail.utoronto.ca

Kind regards,

Jacob Kvasnicka

**Comment by jessexknight** [comment]
Hi! Is this still relevant?

If so, can I reach out to Jacob directly? I have quite a bit of experience in python and ODEs.

**Comment by linamnt** [comment]
Hi @jessexknight Jacob has found a tutor for now, but said you could contact Jacob directly if he needs help in the future. I will close this issue for now. Thanks!
