### ISSUE TITLE
Summer Schedule 2019 + Call for Instructors

### ISSUE THREAD

**Issue by aays** [UofTCoders/studyGroup#446]
Hi everyone! Summer 2019 is now underway and we're excited to get started with our lessons for the summer. Have a look to see which ones you'd like to attend!

We're also on the lookout for instructors for many of the lessons below. If you see a lesson currently without an instructor (designated with **) that you'd like to teach, get in touch about instructing with us -- more info on how to do so below!

Please also feel free to leave comments about lessons that are not listed here but which you'd like to see in the future (or which you'd like to teach yourself).

We will shortly be posting details and installation instructions for each of these lessons in the link below -- be sure to keep an eye out! 
https://github.com/UofTCoders/Events/issues

As with our schedule last summer, these lessons are organized into 'series', such that related topics are grouped together.

Date | Session (previous material linked, if applicable) | Series | Instructor
-- | -- | -- | --
May 30 | Data visualization in R with `ggplot2` | R | Ahmed (@aays)
June 6 | Statistics in R | R | Raul (@ralle123)
June 13 | Intro to Python | Python | Lina (@linamnt)
June 20 | Designing data analysis workflows | Python | Julia (@JuliaSprenger)
June 27 | [Object-oriented programming in Python](https://uoftcoders.github.io/studyGroup/lessons/python/classes/lesson/) | Python | Sara (@SaraMati)
July 4 | Co-working session | N/A | Co-working session at MADLab
July 11 | [Intro to Bash and shell scripting](https://uoftcoders.github.io/studyGroup/lessons/misc/bash-intro/lesson/) | Reproducible science | Frances (@FrancesWong)
July 18 | [Intro to Git](https://uoftcoders.github.io/studyGroup/lessons/git/intro/lesson/) | Reproducible science | Madeleine (@mbonsma)
July 25 | Journal Club - academic workflows | Reproducible science | Group discussion/demos session
Aug 1 | [Collaborating on GitHub](https://uoftcoders.github.io/studyGroup/lessons/git/collaboration/lesson/) | Reproducible science | Ashwin (@shwina)
Aug 8 | Machine learning: introduction to topics | Special topic: machine learning | Haidy (@HaidyGiratallah)
Aug 15 | [Image processing in Python](https://uoftcoders.github.io/studyGroup/lessons/python/image-processing/lesson/) | Special topic: machine learning | Constant (@mori-c)
Aug 22 | Co-working session | N/A | Co-working session at MADLab
Aug 29 | Break - no lesson | N/A | N/A
## Call for Instructors **

We wouldn't be able to hold these weekly sessions without volunteers from the UofT Coders community, and we're always welcoming of any new volunteers who would like to teach or help in other ways. If you'd like to volunteer to instruct one of these sessions (lessons needing instructors indicated with `**`), please reply here or to uoftcoders@gmail.com with the following:

- Which session you'd like to teach
- A quick outline of what you would like to cover. Linked to some of the lessons are previous material that has been developed. You can either reuse the lesson material or adapt it for your purposes.
- Confirm you've read our [Contributing Guidelines for Leading a Lesson](https://uoftcoders.github.io/studyGroup/CONTRIBUTING/#leading-a-lesson)

We will get in contact with you after that to coordinate. Please keep in mind that you DO NOT need to be an expert in the lesson topic to teach. While some familiarity is required, if you'd like to use this as an opportunity to further your understanding of the topic, we highly encourage that as well!

**Comment by ralle123** [comment]
Can I do statistics in R

**Comment by mbonsma** [comment]
I'm interested in either Bash and Shell Scripting (July 11) or Intro to Git (July 18). I'd keep the material mostly the same for either one! (And I've read the Contributor Guidelines.)

**Comment by SaraMati** [comment]
I'm interested in Object oriented Python, June 27, and Collaboration with Github, August 1, (priority given to other instructors that don't have a lesson)

**Comment by mori-c** [comment]
Would love to instruct Image Processing in Python, for Aug 15th

**Comment by aays** [comment]
@mori-c Great to hear! Do you mind emailing us at uoftcoders@gmail.com so we could coordinate further?

**Comment by aays** [comment]
@mbonsma @SaraMati Sounds good - thanks! Like Sara said, I'll wait a bit to see how other instructors respond before assigning either lesson in both your cases.

**Comment by mori-c** [comment]
> @mori-c Great to hear! Do you mind emailing us at [uoftcoders@gmail.com](mailto:uoftcoders@gmail.com) so we could coordinate further?

Should I address it to you @aays?

**Comment by aays** [comment]
@mori-c Sure!

**Comment by aays** [comment]
@mbonsma I have you down for Intro to Git on the 18th, with @FrancesWong teaching the Intro to Bash lesson the week prior - does that work?

**Comment by aays** [comment]
@SaraMati We've got another instructor for Collaborating on GitHub, so I have you down for object-oriented programming on the 27th!

The schedule is now filled - thank you all for volunteering, and I look forward to many awesome summer lessons ahead!
