### ISSUE TITLE
Change of website-url/repo name?

### ISSUE THREAD

**Issue by linamnt** [UofTCoders/studyGroup#46]
Now that our club is approved by Ulife, we came across a problem where our page doesn't show the website link with the correct casing (the capital G in studyGroup) and hence leads to a broken link. 

See here: https://ulife.utoronto.ca/organizations/view/id/126679

For purposes of ease of future use and less confusion, what do you guys think of changing the url to have all lower case? This might be only possible by changing the repo name though, does anyone know how easy or difficult it would be to do this? And if it might cause other problems if it is possible?

Thanks!

**Comment by lwjohnst86** [comment]
I think it would be _much_ easier to get ULife to fix the link than to change the repo name. Anyone that has cloned this repo or set it as an upstream would have to fix it. Which isn't a huge deal for any individual, but given the possible number of upstreams/clones... it becomes a big hassle.

I also don't know how it would affect forks and the fork from mozillascience...

**Comment by lwjohnst86** [comment]
PS: thanks for getting this done!!

**Comment by jladan** [comment]
For the sake of fully informed decisions, I tested by forking and renaming.

Results:
1. There was no warning when I renamed the repo (a good sign)
2. renaming the repo changed the url (as desired?)
3. The link at the top of the repo page (description and website) had to be manually updated.
4. I was able to push and pull successfully (and force push)
5. When pushing/pulling, I received a warning that the location has changed, and instructions on how to change it.
6. The links (I tested a few internal) on the website still worked.

In other tests, with another repo, there was no effect on forks.

**Comment by QuLogic** [comment]
I think it would be better to change the repo name so that the URL would be the plain `https://uoftcoders.github.io/`, but it does produce a somewhat ugly repo name (`uoftcoders.github.io`). Alternatively, add a placeholder repo with a redirect from the plain URL to the correctly cased one, and only give out the short link.

**Comment by lwjohnst86** [comment]
As @QuLogic suggested, I've created a [new repo](https://github.com/UofTCoders/uoftcoders.github.io) with the bare https://uoftcoders.github.io/ URL that redirects to the http://uoftcoders.github.io/studyGroup/ website. 

Does that work ok @linamnt ?

And thanks @jladan for the testing. I didn't realize GitHub fixed all the links like that.

**Comment by linamnt** [comment]
I think that will work! Thanks for all the help everyone!

On Thu, Sep 17, 2015 at 11:22 AM, Luke W Johnston notifications@github.com
wrote:

> As @QuLogic https://github.com/QuLogic suggested, I've created a new
> repo https://github.com/UofTCoders/uoftcoders.github.io with the bare
> https://uoftcoders.github.io/ URL that redirects to the
> http://uoftcoders.github.io/studyGroup/ website.
> 
> Does that work ok @linamnt https://github.com/linamnt ?
> 
> And thanks @jladan https://github.com/jladan for the testing. I didn't
> realize GitHub fixed all the links like that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/46#issuecomment-141120762
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by lwjohnst86** [comment]
Excellent! :smiley:
