### ISSUE TITLE
University of Toronto Libraries - Carpentries Event Support Job Posting

### ISSUE THREAD

**Issue by aays** [UofTCoders/studyGroup#461]
Posted on behalf of University of Toronto Libraries:

---

The UTL Carpentries project team has decided to post a **graduate student job to support various Carpentries events planned for 2020**. 
 
Please help get the word out if you know of someone who might fit the bill.  Or if you are a graduate student, please consider applying! The deadline is **November 19**.
 
The total contract is approximately 90 hours, and the schedule is flexible.

If you are interested, or have any other questions, please contact [May Chan](mailto:ms.chan@utoronto.ca) at University of Toronto Libraries.

**Comment by linamnt** [comment]
This is the actual job posting with more info: https://studentjobs.library.utoronto.ca/index.php/posting/view/2761
