### ISSUE TITLE
Internship Opportunity | Business Intelligence & Analytics Intern

### ISSUE THREAD

**Issue by HaidyGiratallah** [UofTCoders/studyGroup#472]
Princess Margaret Cancer Foundation
Business Intelligence & Analytics Intern needed!

https://www.recruitingsite.com/csbsites/uhncareers/JobDescription.asp?SiteID=10031&JobNumber=857539

The role will support our Foundation-wide data governance, analytics, and reporting services. We are seeking a highly motivated student who is a proactive and resourceful problem solver, with a natural analytical way of thinking.

**Comment by huaqiwen** [comment]
Hi, I am a U of T CS student who just finished first year. I am very interested in this opportunity, however I cannot find any information in the link provided. I attached my resume below.
[Eric_Hua_Resume.pdf](https://github.com/UofTCoders/studyGroup/files/4639164/Eric_Hua_Resume.pdf)

**Comment by linamnt** [comment]
Hi @huaqiwen it seems the job posting is no longer available, so it's possible they have found someone already. @HaidyGiratallah I'm not sure if you are personally involved with the search and whether you could confirm whether we should close the issue?

**Comment by QuLogic** [comment]
I'll assume that the role has been filled at this point.
