### ISSUE TITLE
Fall 2020 schedule

### ISSUE THREAD

**Issue by aays** [UofTCoders/studyGroup#474]
Hi everyone -- hope you've been able to stay safe and healthy. We're excited to finally present our Fall 2020 schedule below, alongside some details about format changes. Given the evolving situation around us, it took us at Coders a fair bit of discussion on how to best hold events online; more on that below. Have a look below to see which sessions you'd like to attend!

Our lessons will now be scheduled from **7-8 pm on Thursday over Zoom**, and will once again happen **every other week**. Zoom links will be provided in the issues for each event (I'll be linking those shortly after this post goes up - edit: the issues are linked below!). That said, the 'in-between' **weeks without lessons will still have Lightning Demos sessions**, where we invite anyone to give a quick 5-10 minute demo on something cool they've been working on, or even a general code demo! These are intended to be friendly and informal and should ideally highlight the coding aspect of what's being presented (although we're obviously keen to hear what folks are working on research-wise). All areas of research and 'complexity' levels are welcome -- there's always something new to be learned all the same. 

Holding all events virtually is obviously uncharted waters for us, and we've been exploring ways to make sure lessons are amenable to this new format. For instance, we recognize that a strict code-along structure is difficult to adhere to over Zoom, especially since not everyone has a dual-monitor setup or something similar. We're therefore actively discussing ways we can make our lessons more accessible and easy to follow over a call (e.g. by providing partially completed scripts with exercises ahead of time, or focusing on more conceptual ideas instead of strict coding). We'll be asking for anonymous feedback via a form after each lesson, and would love to hear from you about how this format goes + how you feel it might be improved as we go along -- especially since we anticipate having to do something similar in the Winter semester as well. Finally, we're also aiming to once again have our lessons take place within an hour -- not because we were unhappy with the 1.5 hour format from last semester, but more so because we recognize Zoom fatigue is a very real thing and want to avoid contributing too much to that! 

Here is the schedule for this semester below. Due to the reduced number of lessons this semester and the changes to the lesson format, we have instructors for each of these already. If you'd still like to teach with us, we're going to be closely monitoring how these lessons go and potentially expanding the schedule next semester to accommodate more lessons, for which we'll definitely be needing instructors. 

Date | Session | Instructor
-- | -- | --
Oct 22 | [Lightning demos + welcome back](https://github.com/UofTCoders/Events/issues/286) | --
Oct 29 | [Reproducible science in RStudio](https://github.com/UofTCoders/Events/issues/287) | Ahmed (@aays)
Nov 5 | [Lightning demos (Python themed)](https://github.com/UofTCoders/Events/issues/288) | --
Nov 12 | [Programming and Data Wrangling in R with the Tidyverse](https://github.com/UofTCoders/Events/issues/289) | Margot (@margot-l)
Nov 19 | [Lightning demos (R themed)](https://github.com/UofTCoders/Events/issues/290) | --
Nov 26 | [Scientific writing with Markdown and Pandoc](https://github.com/UofTCoders/Events/issues/291) | Frances (@FrancesWong)
Dec 3 | [Lightning demos (Data visualization themed)](https://github.com/UofTCoders/Events/issues/292) | --

Looking forward to the semester ahead!

**Comment by jessexknight** [comment]
Thanks @aays!  Hoping I can show off this little ggplot nugget I made, but in case I can't make it, I'll link it [here](https://community.rstudio.com/t/geom-point-with-2-categorical-variables/83886)!
