### ISSUE TITLE
Winter 2021 schedule + call for instructors

### ISSUE THREAD

**Issue by aays** [UofTCoders/studyGroup#478]
Hi everyone, and happy new year! We hope you've been able to stay safe and healthy through the winter holidays. We're excited to present our Winter 2021 schedule below, along with a few further format changes still. Have a look below to see which sessions you'd like to attend!

Our lessons will now be scheduled from **6-7 pm on Wednesdays over Zoom**, and will take place **every week**. We're switching over from Thursdays to Wednesdays based on survey feedback to hopefully allow more of the community to attend. Zoom links will be provided in the issues for each event (linked in schedule). In addition, we'll be running **weekly co-working sessions** hosted by Margot (@margot-l) - time and day TBA. 

Last semester was our first run of entirely online lessons, but based on the experience we've had with it so far (as well as the very helpful feedback from you all) we're happy to say we'll be continuing with the same format. That is: shorter lessons (1 hour timeslots, with ~45 minutes of material so that there's a good bit of wiggle room still) with more emphasis on concepts and slightly less on coding along, so as to better accommodate the 'Zoom experience'. 

Here is the schedule for this semester below. ~~A few of these (marked with **) are still in need of instructors -- if you're interested in teaching these, let us know below!~~ Edit: schedule is set, thanks all!

Date | Session | Instructor
-- | -- | --
Jan 13 | [Introduction to Python][intro-py] | Ahmed (@aays)
Jan 20 | [Introduction to R][intro-r] | Margot (@margot-l)
Jan 27 | [Introduction to Git][intro-git] | Frances (@FrancesWong)
Feb 3 | ~~[Python: scikit-learn][py-scikit]~~ (CANCELLED) | Haidy (@HaidyGiratallah)
Feb 10 | [R: Statistical methods][r-stats] | Amin (@ab2347)
Feb 17 | Break - reading week | n/a
Feb 24 | [Lightning Demos][lightning-demos] | Coders exec
Mar 3 | [Collaborating with Git and GitHub][collab-github] | Ahmed (@aays)
Mar 10 | [Introduction to LaTeX][intro-latex] | Jesse (@jessexknight) 
Mar 17 | [Git: Advanced topics][git-adv] | Elliott (@QuLogic)

Looking forward to the semester ahead! 

[intro-py]: https://github.com/UofTCoders/Events/issues/293
[intro-r]: https://github.com/UofTCoders/Events/issues/294
[intro-git]: https://github.com/UofTCoders/Events/issues/295
[py-scikit]: https://github.com/UofTCoders/Events/issues/296
[r-stats]: https://github.com/UofTCoders/Events/issues/297
[lightning-demos]: https://github.com/UofTCoders/Events/issues/298
[collab-github]: https://github.com/UofTCoders/Events/issues/299
[intro-latex]: https://github.com/UofTCoders/Events/issues/300
[git-adv]: https://github.com/UofTCoders/Events/issues/301

**Comment by aays** [comment]
@jessexknight Would you be interested in tackling either of the latter two Git lessons or Intro to LaTeX? I recall you mentioned being interested in teaching those topics on the survey!

**Comment by jessexknight** [comment]
Thanks @aays !  Yep happy to do the LaTeX one. I've been giving similar talks at the library, based roughly on the resources [here](https://github.com/jessexknight/latex). Note: I won't be covering R markdown at all.

Not super confident about advanced GitHub, but I can try to brush up if you're in a pinch.

**Comment by aays** [comment]
@jessexknight Sounds fantastic! We haven't had a LaTeX one in a while so that'll be super good to have. Re: advanced Git, that one is a bit open-ended (it's currently just listed as 'advanced topics') so if there's virtually anything beyond the scope of intro Git/GitHub it's fair game to teach! I can envision a CI lesson there or potentially a smattering of lesser used commands (stashing, rebasing, git lfs, etc)

**Comment by jessexknight** [comment]
Thanks @aays -- I can only afford to do the LaTeX one right now. The demo repo from the talk last year on continuous integration with pytest, github & travis is [here](https://github.com/jessexknight/mwe-pytest-travis-cov), if that's helpful for anybody looking to do something similar. I haven't used these things in a while and it [looks like](https://developer.okta.com/blog/2020/05/18/travis-ci-to-github-actions) GitHub actions might have replaced Travis CI. Those bastards at microsoft...

**Comment by QuLogic** [comment]
Travis CI basically killed its support for Open Source plans, so that's why no-one uses it any more.
