### ISSUE TITLE
Add link to Discord server on website?

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#483]
It might be nice if the Discord server was linked under the [contact](https://uoftcoders.github.io/studyGroup/#come-say-hi) section on the website.

**Comment by aays** [comment]
Sorry I missed this earlier, but this is a great call! I'll put together a PR tonight or early tomorrow.

**Comment by aays** [comment]
So my local Jekyll installation post-new-laptop-migration refuses to work... could someone else give this a go? @QuLogic perhaps? I'm a little hesitant to push a change to the section without making sure it looks alright first, but can't do that on my computer right now :(
