### ISSUE TITLE
Fall 2021 schedule + call for instructors

### ISSUE THREAD

**Issue by aays** [UofTCoders/studyGroup#490]
Hi all! We hope your Septembers have started off well (and safely!). Below is our Fall 2021 schedule, along with some details about the timeslot/format for Coders events this semester. Have a look below! 

## Schedule

Our lessons this fall will take place from **6-7 pm on Wednesdays on [our Discord server](https://discord.gg/ud984rW9vK)** and will once again take place **every week**. Minus the switch over to Discord, our lessons will be following the same format as last year: 1 hour timeslots, with ~45 minutes of material (so that there's a bit of flexibility still) that emphasize concepts more than coding along to reduce online call burnout. If you've never used Discord before, not to fear -- it's very straightforward to get set up with and doesn't even require an account. More details on Discord can be found below underneath the schedule. 

Here is the schedule for this semester. ~~Some lessons (marked with **) are still in need of instructors -- if you're interested in teaching these, let us know below!~~

Date | Session | Instructor | Host
-- | -- | -- | --
Oct 6 | [Introduction to Python][intro-py] | Elliott (@QuLogic) | Frances (@FrancesWong) 
Oct 13 | [Introduction to R][intro-r] | Tara (@tarahenechowicz) | Vicki (@vmzhang)
Oct 20 | [Introduction to Git][intro-git] | Raul (@ralle123) | Ahmed (@aays)
Oct 27 | [R: Data visualization with ggplot2][int-r] | Vicki (@vmzhang) | Tara (@tarahenechowicz)
Nov 3 | [Python: machine learning with scikit-learn][int-python] | Haidy (@HaidyGiratallah)  | Amin (@ab2347)
Nov 10 | Break - reading week | n/a
Nov 17 | [Pandoc and Markdown][pandoc-markdown] | Frances (@FrancesWong) | Haidy (@HaidyGiratallah) 
Nov 24 | [Lightning demos][lightning-demos] | Coders exec
Dec 1 | [Creating websites with RStudio and blogdown][websites-blogdown] | Ahmed (@aays) | Vicki (@vmzhang) 

[intro-py]: https://github.com/UofTCoders/Events/issues/304
[intro-r]: https://github.com/UofTCoders/Events/issues/305
[intro-git]: https://github.com/UofTCoders/Events/issues/306
[int-r]: https://github.com/UofTCoders/Events/issues/307
[int-python]: https://github.com/UofTCoders/Events/issues/308
[pandoc-markdown]: https://github.com/UofTCoders/Events/issues/309
[lightning-demos]: https://github.com/UofTCoders/Events/issues/310
[websites-blogdown]: https://github.com/UofTCoders/Events/issues/311

## More on Discord

The main change to our format this semester is probably the move to **Discord** over Zoom. Discord is a free service (and doesn't even require an account!) that allows users to host voice and video calls. Discord can be run as a standalone application or even just in your browser. In addition, Discord also features much richer chat functionality, and we've found that leads to a better learning experience after 'test driving' it during a Carpentries workshop this past summer. See below for an instructional poster courtesy of @FrancesWong on how to use it! 

[How to use Discord to attend UofT Coders events (pdf)](https://github.com/UofTCoders/studyGroup/files/7247064/discordIntro_general2021.pdf)

## More things to come! 

We're also excited to soon release more info on **a peer mentorship program for this year** as well as resuming our regular **co-working sessions**. Details are currently TBA, but do stay tuned! 

Looking forward to the semester ahead!

**Comment by ralle123** [comment]
can I take introduction to git?
--
Thanks,

Raul Samayoa
https://ca.linkedin.com/in/rsamayoa

**Comment by aays** [comment]
@ralle123 For sure! I'll add you to the schedule
