### ISSUE TITLE
Introduction to Git

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#5]
## Code-along 1 - Introduction to Git

Workflows, version control - what's the deal with [Git](https://git-scm.com/)? Come out to an Intro to Git session presented by @lwjohnst86. No prior Git experience is necessary, all are welcome.

**When:** Thursday, June 18, 2015, 6 pm - 7 pm
**Where:** MP 408 ([Mclennan Physical Labs](https://www.google.ca/maps?q=mclennan+physical+labs&es_sm=122&um=1&ie=UTF-8&sa=X&ved=0CAcQ_AUoAWoVChMIoI3D7v-RxgIViEySCh34tAQ3), in the Burton tower)
**What to bring:** Computer, charged if possible, with Git installed (instructions below). If you don't have a Github account yet, now would be a good time to do that too.
### Git

Installation instructions for Git can be found on the
[Git download site](http://git-scm.com/book/en/Getting-Started-Installing-Git)
- On Windows: Download the `.exe` file from this
  [Github link](http://msysgit.github.io) and run it.
- On Mac: To use the graphical Git installer, download from this
  [SourceForge link](http://sourceforge.net/projects/git-osx-installer/)
- On Linux: Use your respective package manager (for example, if you
  use Ubuntu or Debian, run this code: `sudo apt-get install git`)

**Comment by mbonsma** [comment]
Dominique was going to bring cookies, but she's away Wednesday through Friday. Is anyone else willing and able to bring some kind of snack?

**Comment by lwjohnst86** [comment]
For tomorrow's session, is any intermediate/advanced git user coming? Doing live coding with those new to shell/git/etc is always difficult with multiple instructors/helpers, let alone solo. Anyone who has done a Software Carpentry workshop knows there are always issues that arise, especially with Git. SWC workshops always have several helpers, so I am hoping others can come along and help out for this session!! :)

**Comment by cczhu** [comment]
I can bring cookies (not homemade, sadly) if the job remains untaken!

**Comment by mbonsma** [comment]
Thanks @cczhu, that would be great!

**Comment by lannajin** [comment]
Thanks for hosting the Git session today--it was a useful start to Git and definitely piqued my interest! Although since I'm not of the computer science or (astro)physics background, I struggled a bit with some jargon. Can you guys recommend a good resource for clarifying the conceptual framework of Git--in particular, how the different staging processes work and why they are there, etc.?

**Comment by lwjohnst86** [comment]
Great question! I am also not of the computer sci or physics background either (nutritional sciences), but I found this https://git-scm.com/book/en/v2/Getting-Started-Git-Basics#The-Three-States (clarify, this is the relevant section) really useful. [YMMV](http://www.urbandictionary.com/define.php?term=ymmv) however.

**Comment by dchandan** [comment]
@lwjohnst86 reference is a good one, i've found it useful myself (here is the link to the book: https://progit.org/). The book itself is quite good. I've also found this Atlassian tutorial helpful: https://www.atlassian.com/git/tutorials/

**Comment by mbonsma** [comment]
Event is now in the past.
