### ISSUE TITLE
Calling presenters for Python lightning demos - Nov 5

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#51]
The code-along [scheduled](https://github.com/UofTCoders/studyGroup/wiki/Schedule---Fall-2015) for November 5 is a series of short demonstrations on Python-related topics. Ideally, 5-6 people would each give a 5-10 minute demo of a Python tool they use or a neat trick they want to share. I know of about 3-4 people that could share, but we need more! 

Comment here if you or someone you know is interested in sharing a demo. You don't have to be an expert; in fact, if you just learned something cool you'll be better at explaining it again for new people.

**Comment by jdpigeon** [comment]
I'd be happy to do a quick demo on Python Pandas DataFrames. They're super handy and their GroupBy function could be a flashy trick to show off.

Cheers,
Dano

**Comment by mbonsma** [comment]
That would be awesome! I added you to the schedule.
