### ISSUE TITLE
Campus Recognition

### ISSUE THREAD

**Issue by atavasoli** [UofTCoders/studyGroup#6]
Hi everyone! 

In our first meeting we talked a bit about getting our group recognized as an official campus organization. This comes with a lot of perks like access to facilities and funds allocated for student groups (and remember: money = cookies). 

Here are a few applications I'll be working on. I just wanted to reach out and see if anyone has any other suggestions that I might have missed. I don't have a lot of expertise outside of the engineering faculty, so if your department has student initiative funding, let me know!  

Student Initiative Fund (due Sept. 18th):
https://www.studentlife.utoronto.ca/Student-Initiative-Fund.htm

ULife:
https://www.ulife.utoronto.ca/page/view/slug/apply

GSU donation request:
https://www.utgsu.ca/funding/donation-requests/

Engineering society funding/affiliation (opens in July 2015): 
http://skule.ca/clubs/start/

UTSU group affiliation:
http://utsu.ca/apply-to-be-a-club/

Co-Cirricular Record:
https://ccr.utoronto.ca/home.htm

**Comment by mbonsma** [comment]
This is awesome Alex!

**Comment by mbonsma** [comment]
@atavasoli, how's the Student Initiative Fund app looking? Anything I or we can do to help?

**Comment by mbonsma** [comment]
Is anyone interested in helping us get recognized as a club? Info on how to apply [here](https://www.ulife.utoronto.ca/page/view/slug/apply).

**Comment by linamnt** [comment]
I've done stuff like this before so I can help out! Did we have a
constitution drafted up at some point? Or should I try to draft one up now?

On Tue, Sep 8, 2015 at 1:24 PM, mbonsma notifications@github.com wrote:

> Is anyone interested in helping us get recognized as a club? Info on how
> to apply here https://www.ulife.utoronto.ca/page/view/slug/apply.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/6#issuecomment-138640429
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by lwjohnst86** [comment]
We have one started here: https://github.com/UofTCoders/studyGroup/pull/20

**Comment by lwjohnst86** [comment]
Are you fairly familiar with using git? Have you made a fork of this repo? If so, you can get @atavasoli files via using git while in the `studyGroup` folder in your terminal:

```
git checkout -b atavasoli-patch-1 gh-pages
git pull https://github.com/atavasoli/studyGroup.git atavasoli-patch-1
```

You now have the constitution. We've comments made comments on it in the pull request that need to be incorporated. 

After you've made changes, done `git commit`, you need to push that up to your account:

```
git checkout gh-pages
git merge --no-ff atavasoli-patch-1
git push origin gh-pages
```

Then in GitHub, submit a pull request.

**Comment by linamnt** [comment]
I'll try! Otherwise, I can download a copy from the site as she did, and
incorporate the changes and then submit the new copy to the git. Thanks for
the instructions!

On Tue, Sep 8, 2015 at 2:07 PM, Luke W Johnston notifications@github.com
wrote:

> Are you fairly familiar with using git? Have you made a fork of this repo?
> If so, you can get @atavasoli https://github.com/atavasoli files via
> using git while in the studyGroup folder in your terminal:
> 
> git checkout -b atavasoli-patch-1 gh-pages
> git pull https://github.com/atavasoli/studyGroup.git patch-1
> 
> You now have the constitution. We've comments made comments on it in the
> pull request that need to be incorporated.
> 
> After you've made changes, done git commit, you need to push that up to
> your account:
> 
> git checkout gh-pages
> git merge --no-ff atavasoli-patch-1
> git push origin gh-pages
> 
> Then in GitHub, submit a pull request.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/6#issuecomment-138652946
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by QuLogic** [comment]
> ```
> git checkout -b atavasoli-patch-1 gh-pages
> git pull https://github.com/atavasoli/studyGroup.git patch-1
> ```

That `patch-1` should be `atavasoli-patch-1`, I think?

**Comment by lwjohnst86** [comment]
This is the code used by Github, so I assume it is correct

On 8 September, 2015 3:01:11 PM EDT, Elliott Sales de Andrade notifications@github.com wrote:

> > ```
> > git checkout -b atavasoli-patch-1 gh-pages
> > git pull https://github.com/atavasoli/studyGroup.git patch-1
> > ```
> 
> That `patch-1` should be `atavasoli-patch-1`, I think?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/UofTCoders/studyGroup/issues/6#issuecomment-138671063

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by linamnt** [comment]
An address is required for application, any ideas what address would be most appropriate? It's mainly a technical thing so I don't think it matters too much, perhaps I could do the physics building as that is where most meetings are held so far?
