### ISSUE TITLE
Software Carpentry - Call for Applications

### ISSUE THREAD

**Issue by lcoome** [UofTCoders/studyGroup#63]
Hi Everyone,

We are trying to put together a group application for Software Carpentry instructor training. 

Software Carpentry is a volunteer organization that runs workshops aimed at teaching scientists basic computing skills like automating tasks, programming in Python and R, and version control using Git. 

Although there is currently a waitlist for instructor training, Software Carpentry has announced a call for applications for instructor training in December. They are requesting that interested instructors apply in groups of 3-8 (ideally). Interested groups must be able to commit to attend instructor training together on December 7th & 8th, and jointly run one workshop no later than April 1st, 2016. 

They appear to be looking for candidates who are either on the current waiting list or demonstrate competence in the topics they will teach. It also appears that they will give preference to applicants who have attended a SWC workshop in the past, volunteered as helpers or instructors, or are involved in Python/R groups such as ours.

**Application Steps:**
- Fill out a survey **as a group** (link found on the application page) with a cover letter expressing interest in attending training
- Fill out an **individual survey** with steps that include:
  - Watching one of the videos listed in the instructor training application page and submitting a paragraph of feedback on the video
  - Submitting a small pull request to a specified GitHub repository with a text file containing a sentence or two that describes the type of work you do (and submit the name of this file as part of the application)

The application deadline is **November 18th**. We plan to collaborate on the cover letter as a group. Madeleine has uploaded a template on Github that anyone can work on. If you’d like to be a part of the application, please e-mail Madeleine and Lindsay at m.bonsma@mail.utoronto.ca and lindsay.coome@mail.utoronto.ca so we can keep track of how many people are interested.

More information on the selection criteria and application process, including links to the application surveys, can be found here:

http://software-carpentry.org/blog/2015/10/call-for-instructor-training.html

Thanks! 
Lindsay

**Comment by mbonsma** [comment]
I'm working on reserving a room and will update the cover letter when it's finalized.

**Comment by mbonsma** [comment]
Also the cover letter is PR #62 - feel free to add your name and comment!

**Comment by ghost** [comment]
Great I'll do mine this week

**Comment by dcwalk** [comment]
Hiya, I've been a bit of a lurker but am keen to jump on this thread. I'm involved with a group on campus [AIS](http://ais.ischool.utoronto.ca/), based out of the Faculty of Information and supporting professional grad students develop technology skills.

We had a SWC workshop last February run by Greg and would love to be a host again if you are looking for a place to run a session! There aren't as many students with research interests, but many plan on working with data in a library, records management, system design capacity (I believe there may be a Data Carpentry workshop on the horizon, but this seems like a potential opportunity to collaborate).

Further, since a few of us attended last session I could see if there are and AIS members who are keen to attend a training to become a volunteer if that would be appropriate?

**Comment by mbonsma** [comment]
@dcwalk, great to hear from you! Your group looks very cool, and it would be awesome to collaborate. Could we potentially add you as a host in our [cover letter](https://github.com/UofTCoders/studyGroup/pull/62/files)? (We're supposed to plan and hold at least one SWC session before April 2016.)

Training is open to anyone interested, especially if they're involved in a group like yours or ours or have attended / helped with Software Carpentry before. There's no cap on attendance, so the more the merrier. The only thing is that if we have more than 10 people, we'll need to hold at least two SWC workshops before April.

**Comment by dcwalk** [comment]
@mbonsma 👌 awesome, I've passed on the request about having us as a host group to the rest of the AIS exec, would it be alright if we gave you an answer by **Nov 14**?

Regardless, I signed up to attend the training! My background is more python/bash but have done some stuff in R and could brush up as needed...?

**Comment by mbonsma** [comment]
Yes, that'll leave enough time to add you to the cover letter for sure. Thanks!

**Comment by mbonsma** [comment]
@linamnt, @thesarahmeister, @lcoome, I added you all to the [cover letter](https://github.com/UofTCoders/studyGroup/pull/62/files) (and updated the room - we got one in OISE).    If you want to change your description in the 3rd paragraph, that's totally okay.

**Comment by pipitone** [comment]
Hey @mbonsma, I was just talking with some folks at CAMH who would be interested in doing the instructor training as well. Can we pile in with you all?  We could certainly host/help host the second instructor training at CAMH also.

**Comment by mbonsma** [comment]
@pipitone, absolutely! Feel free to line comment with names and brief descriptions on the [cover letter](https://github.com/UofTCoders/studyGroup/pull/62/files).

**Comment by mbonsma** [comment]
So we just noticed there's a [clarification](http://software-carpentry.org/blog/2015/11/clarifications-about-call-for-instructor-training.html) to the training, and groups are now capped at 10 people. So it'll be first-come-first-served from this point on, so if you're interested, add your name to the [cover letter](https://github.com/UofTCoders/studyGroup/pull/62/files) (line comment) and we'll go from there!

**Comment by QuLogic** [comment]
I wasn't going to but I realized TAing finished the week before that, so I sent a PR over your way.

**Comment by dcwalk** [comment]
Just an update from AIS group participation: we are more than keen to add ourselves as a host organization. I think it'll just be me and maybe one more person looking to attend the training. 

I've made a line comment with wording suggestions covering these facts on the [cover letter](https://github.com/UofTCoders/studyGroup/pull/62/files), lemme know what else you need, and in terms of coordinating if you want to touch base off github! Look forward to working together.

**Comment by mbonsma** [comment]
Down to the last two days! 

@lcoome, @linamnt, @thesarahmeister, @QuLogic, @ricardoharripaul, @derekhoward, @dcwalk:    

If you have not yet fulfilled the individual portion of the application and your name is on the list, please do so [here](https://docs.google.com/forms/d/1aXlqxFk6uJbB0k7QICteI5CP3lVczZKyjmgeNibX0Oc/viewform) (I know most of you have!)
.
The steps are, to recap:
- Watch one of the two videos in the above link and type a paragraph response.
- Submit a PR with a small text file to the [SWC training repo](https://github.com/swcarpentry/training-prep-2015-09).

Also, please check the group cover letter (PR #62) to make sure that your description is to your satisfaction and add anything you think would help.  

**We now need to decide on which workshops we'd like to host next year, and who will teach what!** We'll need to host at least 2, since we have more than 5 people. My vote is for Git and Python, but we can be flexible. What do you all think?

For reference:
"Groups will be selected based on:
- Group members were involved in SCF/DC, e.g. members were learners, helpers or instructors in a workshop, members have opened issues or pull request to one of SCF/DC lessons.
- Group members were involved in a group that organizes Software Carpentry-like workshops, e.g. The Hacker Within, Python and R local user groups.
- The group's plan for the follow-up workshop."

**Comment by dcwalk** [comment]
@mbonsma looks good!

I'm comfortable with both git and python, so happy to go down one either, though I'm not 100% on the distinction between Helper and Instructor -- both will be from those of us attending the training, yeah?

**Comment by mbonsma** [comment]
@dcwalk, I'm also not sure on the distinction. If possible it would be great to have everyone who attends training have a chance to be the bona fide instructor - maybe over the course of the workshop we could rotate. I think for now we should just list the people who want to be involved with either one, and we can work out the details closer to the workshop.

**Comment by ghost** [comment]
I can teach R for sure. Also you could add to the cover letter that I've taught a course on R through Graduate Professional Skills at U of T :)

**Comment by mbonsma** [comment]
I'll add it, that's great!

Do you think we have to teach only two workshops, or could we do three? If we do three, it would make sense to do a Python one, a Git one, and an R one.

**Comment by ghost** [comment]
I feel like we could whip out 3, depending on how many instructors we need per session

**Comment by mbonsma** [comment]
If we did Python, Git and R, these are the people I assume would potentially want to be involved in each:

**Python**:
Madeleine
Lina
Elliott
Ricardo
Derek
Dawn

**Git**:
Madeleine 
Elliott
Dawn

**R**:
Lindsay
Sarah

What are your preferences - anyone else interested in R or Git? (We could probably get someone else from UofT coders as a helper for R if it comes to that.)

**Comment by linamnt** [comment]
I could help out with R as well.

On Tue, Nov 17, 2015 at 11:38 AM, Madeleine Bonsma <notifications@github.com

> wrote:
> 
> If we did Python, Git and R, these are the people I assume would
> potentially want to be involved in each:
> 
> _Python_:
> Madeleine
> Lina
> Elliott
> Ricardo
> Derek
> Dawn
> 
> _Git_:
> Madeleine
> Elliott
> Dawn
> 
> _R_:
> Lindsay
> Sarah
> 
> What are your preferences - anyone else interested in R? (We could
> probably get someone else from UofT coders as helpers for R if it comes to
> that.)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/63#issuecomment-157425232
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by lwjohnst86** [comment]
If there is a lack of helpers, I could be a helper for any of the 
sessions (Python, Git, R)... Unless there is something in the 
application that prevents that.

**Comment by mbonsma** [comment]
@lwjohnst86, I don't think there is, so that would be great! I think our numbers are looking alright for R and Python now, I'll add you to the Git one.

**Comment by dcwalk** [comment]
Looks good!

If you think it would be a benefit you could add that I've taught command line (bash) workshops before and organized/volunteered at sessions for open source, python & linux skills before.

**Comment by mbonsma** [comment]
Thanks @dcwalk, done! 

Thanks everyone for the comments! Since the deadline is tomorrow, how about we say that we'll be done at 5 pm tomorrow? At 5 pm, I'll submit the cover letter to the group survey.

**Comment by hgibling** [comment]
Good luck guys!

> Do you think we have to teach only two workshops, or could we do three? If we do three, it would make sense to do a Python one, a Git one, and an R one.

I'm curious... for the workshop(s) you're required to run in the new year, do they have to be full-sized SWC workshops? I.e., a 2-day workshop that teaches a programming language (R/Python), a version control system (git/mercurial), and bash (and optionally SQL)?

**Comment by katieannemills** [comment]
Hey folks,

Thanks for getting this application together! To the last couple of questions, yes, they're expected to be full sized workshops; that means nominally half a day of git, half a day of shell, and one full day of python or R; optionally, half of the python or R can be swapped out for SQL. Git and Shell are mandatory components of all SWC workshops. Let me know any other questions, and good luck!

**edit**: or, yes, mercurial instead of git - but definitely one of those.

**Comment by hgibling** [comment]
Thanks for the clarification, @BillMills.

So you guys would have an R/git/shell workshop, and a Python/git/shell workshop. I'd be happy to help if needed!

**Comment by mbonsma** [comment]
Thanks @hgibling for catching that, and @BillMills for clarifying! I updated the letter to just the two workshops - one python, one R.

**Comment by lcoome** [comment]
Looks great everyone! I can definitely instruct for the R/git/shell workshop and be a helper for the Python one.

**Comment by mbonsma** [comment]
All done! (The deadline is 11:59 pm UTC, which is in just under two hours, just in case anyone still has individual stuff to submit.)

**Comment by QuLogic** [comment]
No, the deadline is [UTC-12](http://software-carpentry.org/blog/2015/10/call-for-instructor-training.html#comment-2365487478).

**Comment by mbonsma** [comment]
With the correction to UTC-12, the deadline is 7 am EST on Nov 19 (14 hours from now, not 2), by my calculation.

**Comment by QuLogic** [comment]
But best to get it done sooner than later :wink:

**Comment by QuLogic** [comment]
Based on our application, @thesarahmeister and @ricardoharripaul, please remember to submit your PR to the training repo today!

**Comment by ghost** [comment]
I did?

**Comment by linamnt** [comment]
Just a heads up, the file in your PR doesn't seem to be a .txt file on my end. Not sure if they even care/are strict about that though.

**Comment by ghost** [comment]
fixed.

**Comment by mbonsma** [comment]
**We're accepted!!** Just got the email 5 minutes ago. Here it is:

Hi,

The selection for Software Carpentry Instructor Training in December was very difficult
and we are happy to inform you that the mentoring subcommittee
has selected your group for Software Carpentry Instructor Training in December.

We like to introduce you to Greg Wilson that will be the trainer instructor for your group.
In the next week we would like that you and Greg Wilson:
1.  agree on a time for the training and
2.  test the video conference room.

We also want to know if will be possible that two small groups from Ontario,
one with 3 members and the other with 5 members,
join your group in Toronto for the instructor training.
Please let us know as soon as possible so we can contact the groups.

If you have question, let us know.

Congratulations, we look forward to meeting you and having you join our community.

Thanks,
Raniere Silva

**Comment by mbonsma** [comment]
The rooms we got don't have projectors or video conferencing built-in, so we either would need a different room or to just use someone's computer. I'll reply and ask about that. 

What do you guys think about having the other groups join?

**Comment by ghost** [comment]
I have no issues letting other groups join! I thought the days for training were Dec 7 & 8? Super excited!

**Comment by abbycabs** [comment]
If you need video conferencing, happy to host you in the Mozilla Offices. However, I can only host Dec 14 - 18 (out of town rest of the month).

**Comment by mbonsma** [comment]
@acabonoc, that would be amazing! Others, are you available at all Dec 14-18? I'll check with Greg, our contact at SWC, if we would be possible to switch the dates. 

Otherwise, we'll need a good microphone, camera, speaker system, and projector.

**Comment by ghost** [comment]
Yeah I could do some but not all of those days (but the workshops are only two days, right?)

**Comment by mbonsma** [comment]
Just heard back, the dates are fixed for Dec 7-8, so we'll need to figure out our own A/V. I'll do some digging, but if anyone knows an easy way to get a microphone, camera, speaker system, and projector, let me know.

**Comment by pipitone** [comment]
We have a meeting room at CAMH that might do the trick. @lcoome was there yesterday so can speak to it's fit-ness. It has a projector, and video camera set up that I think y'all could use. I'll see if it's available those days.

**Comment by mbonsma** [comment]
@pipitone, thank you!

Also, the group of 5 joining us from Waterloo has asked if we might have couch or floor space so that they can spend the night. I have a couch and floor, and is anyone else interested in hosting some travelers?

**Comment by dcwalk** [comment]
There is probably a space at the Faculty of Information (Bissell) we could use as well @mbonsma ... let me know if you need me to check once @pipitone gets back?

Also, I am relatively close to campus and could host 2-3 people on couch and floor if needed!

**Comment by pipitone** [comment]
@mbonsma @dcwalk The CAMH room I had in mind has teleconferencing equipment that _only_ works on the Ontario Telehealth Network. :-) 

So, I'm sorry, but I don't have a room with equipment for you to use at CAMH.

**Comment by mbonsma** [comment]
@pipitone thanks for checking! @dcwalk, would you be able to check on your space? I'm working on seeing if there's a room in Physics we could use, but I don't know if we can get both full days. I'm also looking into requesting A/V equipment to be brought to our currently booked room.

**Comment by pipitone** [comment]
@mbonsma I can provide a projector if needs be. And, I do have a kewl web cam to use if all else fails. ;-)

**Comment by mbonsma** [comment]
@pipitone, thanks! We may take you up on the projector. I have a decent webcam as well that we could try. It's possible its microphone and camera are good enough, so if that's the case then all we'd need are some speakers, not even necessarily awesome speakers. 

I booked a room in physics that has teleconferencing equipment for the Tuesday but it wasn't free on the Monday.

**Comment by dcwalk** [comment]
Hey! @mbonsma I emailed our facilities manager. I have a room with A/V (projector/speakers), just confirming that we could set up video/microphone (which we should be able to).

However, he isn't in until Monday so I won't get an answer until Monday afternoon or Tuesday.

**Comment by dcwalk** [comment]
Also -- what was the chosen times for training on Dec 7/8? Are we running 9am - 5pm? 
I've got some evening things that have come up I am trying to schedule around :tired_face:

**Comment by QuLogic** [comment]
I think that's what we need to decide. All we know is "all day", I think.
For me, I don't think any time earlier than 9 is good because of the
commute (and I really prefer 10, but that depends on how late it runs.)
Most everyone else is nearer to campus though.

**Comment by mbonsma** [comment]
9-4 is the preferred time for Greg from SWC. How does that sound?

**Comment by mbonsma** [comment]
@dcwalk, would we be able to test the A/V on Wednesday or Thursday sometime? Thursday afternoon is best for me, but if you're willing to do the test then it can be whenever works for you, and I'll put you in touch with Greg.

**Comment by mbonsma** [comment]
We also have the option of renting a projector and sound system, although it's kinda expensive - $126 for the two days.

**Comment by hgibling** [comment]
What's the total size of the group? I'll ask around to see if I can find something for you guys if @dcwalk's lead doesn't pan out

**Comment by mbonsma** [comment]
I think we are 17 - 9 in our group, then the two other groups of 5 and 3 joining us.

**Comment by mbonsma** [comment]
We have a new request to start at 8:30 am instead of 9. Does that work for everyone?

@dcwalk, any word on the room? We need to nail that down as soon as possible so we can do the A/V test and coordinate with the others. Right now we're scheduled to do the A/V test on Thursday at 1 pm.

**Comment by mbonsma** [comment]
@edickie and @derekhoward, can you send me your email addresses (m.bonsma@mail.utoronto.ca)? Greg from SWC will be sending out readings soon.

**Comment by edickie** [comment]
You can reach me (@edickie) at erin.w.dickie@gmail.com

**Comment by dcwalk** [comment]
@mbonsma I just followed up with out facilities manager again. No answer yet, sorry!
Also starting for 8.30 works for me.

**Comment by linamnt** [comment]
Do we want to use our Ulife privileges to book some rooms as backup just in
case the other options fall through?

I did a quick search on campusroomfinder and there are rooms in OISE
available on those days with projectors. If we also need speakers, I can
grab a set from home and that can plug into a laptop if need be?

On Tue, Dec 1, 2015 at 11:02 AM, dcwalk notifications@github.com wrote:

> I just followed up with out facilities manager again. No answer yet, sorry!
> On Dec 1, 2015 10:33 AM, "edickie" notifications@github.com wrote:
> 
> > You can reach me (@edickie) at erin.w.dickie@gmail.com
> > 
> > On Tue, Dec 1, 2015 at 10:30 AM, Madeleine Bonsma <
> > notifications@github.com>
> > wrote:
> > 
> > > @edickie https://github.com/edickie and @derekhoward
> > > https://github.com/derekhoward, can you send me your email
> > > addresses (
> > > m.bonsma@mail.utoronto.ca)? Greg from SWC will be sending out readings
> > > soon.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/UofTCoders/studyGroup/issues/63#issuecomment-161002161>
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/UofTCoders/studyGroup/issues/63#issuecomment-161002755>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/63#issuecomment-161013493
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by mbonsma** [comment]
I already booked rooms in OISE, but they don't have projectors, which is why we were going through all this. I'll try again to get ones with projectors.

**Comment by linamnt** [comment]
Oh I see, okay!

**Comment by mbonsma** [comment]
It looks like according to the room booking website that our rooms do have projectors. In a pinch, then, we can use my webcam and Lina's speakers. hooray!

**Comment by mbonsma** [comment]
Let me summarize our options just so people don't have to read a million messages:
1. Room from Faculty of Information, arranged by @dcwalk. Preferably has everything we need (projector, camera, mic, speakers), and is available starting at 8:30 AM.
2. Rooms in OISE that we already have booked. They have projectors and speakers, but we would need to pay to access them ($63 per day). Another issue there is that the room booking starts at 9 am and can't go earlier, at least not officially.

**Comment by dcwalk** [comment]
Okay, so I have room(s)!

For sure we have the mic & camera, they will need to be attached to a computer that we will have to supply (I can borrow one from the Faculty if needed though not sure if we could install the BlueJeans app to it as the HD is frozen).

The only lingering issue is that we might be in two rooms, one per day (they are right beside each other though), with one having the better set up for teleconferencing. The gear will work in both and they have capacity 30: 

**BL 307 (Mon) and BL310 (Tues)**
Faculty of Information, Claude T. Bissell building
140 St. George St
Toronto, Ontario

Building will be open to public, fob access which I have to the room.

@mbonsma or whoever needs to test the gear: Friday would be easier for me than Thursday, you have my email to set that up?

**Comment by mbonsma** [comment]
@dcwalk, thank you so much, this is great! (I sent you an email about testing.)
