### ISSUE TITLE
Video streaming of lessons

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#74]
I know some other groups (SFU in particular) do an online stream of code-alongs and post the videos. We've had some requests for that, so what do people think about trying to set that up?

**Comment by lwjohnst86** [comment]
I think that would be useful for establishing an archive of lessons so others can check them out. We could link it to the website some how. Would also be good as a record for those doing the code-along, maybe for their CV or something. And to see how to improve on doing the code-along. I know I would use it for that...

**Comment by lwjohnst86** [comment]
First one has been [done for this code-along](https://github.com/UofTCoders/Events/issues/39), hopefully (more likely) these will continue :)
