### ISSUE TITLE
Python-ized R lessons

### ISSUE THREAD

**Issue by QuLogic** [UofTCoders/studyGroup#81]
I think @mbonsma and @derekhoward asked about these. I don't really know R and I'm not an expert in any of the Python packages used here, but I tried my best to convert these lessons to their Python equivalents. They are as close to 1-to-1 as possible, so maybe not the most efficient. I'm also not trying to say that either Python or R is better than the other; you can decide that for yourself based on your use case. The linked gists contains notebooks for both the R lesson and the Python conversion (but they are not really lessons themselves!)
- @lwjohnst86's [Introduction to R](https://gist.github.com/QuLogic/c65772479f6101393fc3)
- @lcoome's [Basic Stats in R](https://gist.github.com/QuLogic/4477f0e884ebd29ffe80)
- @thesarahmeister's [Introduction to ggplot2](https://gist.github.com/QuLogic/6c168deedeab0a7c2c96)

If you click the "Download ZIP" button on the gist, you should be able to get the notebooks and the datasets (I included CSVs of the R data since the Python libraries don't include the same datasets.)

**Comment by jdpigeon** [comment]
Thank you!

**Comment by lwjohnst86** [comment]
I've wanted to and have started to put these on the site. Hopefully will finish that soon
