### ISSUE TITLE
Schedule for Winter 2016 - instructors needed!

### ISSUE THREAD

**Issue by mbonsma** [UofTCoders/studyGroup#83]
We have a [tentative schedule](https://github.com/UofTCoders/studyGroup/wiki/Schedule-Winter-2016) for this term based on votes from the lesson topic survey. Instructors are needed for several topics, many of which have pre-made lessons available from the [Mozilla Study Group lesson bank](http://mozillascience.github.io/studyGroupHandbook/lessons.html#lessons).

If you'd like to present but don't see the topic you want on the day you want it, not to worry! We can shuffle things around and adjust the topics to suit you. 

Not sure if you've got the necessary expertise to present? You do! The best teachers are often not experts, because they are more aware of what it's like to learn the topic and don't suffer from "expert blindness". 

Comment here or send me an email (m.bonsma@mail.utoronto.ca) if you're interested in leading a code-along.

**Comment by jladan** [comment]
I'd be willing to tackle "building packages in Python" or LaTeX.

**Comment by mbonsma** [comment]
@jladan do you have a preference? If not, can I slot you in for Python packages?

**Comment by dcwalk** [comment]
hey! I'd be able to handle "**Web design with Jekyll/Github Pages**" if no one else is keen to!

**Comment by jladan** [comment]
I have no preference.

**Comment by mbonsma** [comment]
@jladan, you're in for Python packages. @dcwalk, great! You're in the schedule.

**Comment by linamnt** [comment]
Would we be able to move Python Classes to Jan 28? I don't think I am able to stay for a whole hour on Feb 18th as scheduled. It could also give us more time to find potential instructors for the R lessons.

Though since it would make sense to group the two Python lessons together (classes, then package making), would @jladan be okay with instructing the week after on Feb 4th? Sorry the trouble!

**Comment by mbonsma** [comment]
Sure thing, although sad for me because I won't be around on Jan 28 or Feb 4.

**Comment by linamnt** [comment]
Oh no :( I could also teach the 21st (and might actually be better for me)?
and we could move the co-working session for a week?

On Mon, Jan 11, 2016 at 1:41 PM, Madeleine Bonsma notifications@github.com
wrote:

> Sure thing, although sad for me because I won't be around on Jan 28 or Feb
> 4.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UofTCoders/studyGroup/issues/83#issuecomment-170648314
> .

## 

Lina Tran
MSc. Candidate | Frankland Lab
Department of Physiology
University of Toronto

**Comment by mbonsma** [comment]
Okay, let's do that, and then bump the R sessions down. I don't think we need to have the python and R sessions back-to-back necessarily.

**Comment by lwjohnst86** [comment]
[Winter schedule](https://github.com/UofTCoders/studyGroup/wiki/Schedule-Winter-2016) has been filled, plus it's nearly summer!!!
